### ISSUE TITLE
Record fields do not support completion/rename/go-to-declaration

### ISSUE THREAD

**Issue by klazuka** [klazuka/intellij-elm#1]
Record fields do not currently support:
- code completion
- find usages
- go-to-declaration

Implementing these features correctly requires that we resolve a record instance to its type definition, which means that we need static type inference in the general case.

I would like to implement the Elm type system in the plugin, but that's a big job.

As a stop-gap solution for code completion, we may want to provide code completion suggestions based on the Record types that are visible in expression scope, without worrying about whether it is or is not the type that the value actually resolves to.

**Comment by DoctypeRosenthal** [comment]
Any chance we see this feature in the near future? 



(I thought about some clever word plays with "feature" and "future" but no chance man!)

**Comment by klazuka** [comment]
Yes! Most of the hard work needed to implement this has already been done by AJ. And we do currently support record field completion when accessing a record field. 

The last foundational things remaining are:

- allow parse errors during inference (needed for good code completion)
- figure out how to make reference resolve be able to use type inference without creating an infinite loop (needed for rename / find usages)
- implement unification in type inference (needed to finish type inference)

Once those things are done, there would need to be some additional work to actually finish the work described by this issue. I would hope to have this done by the summer. But certainly in 2019!

**Comment by DoctypeRosenthal** [comment]
Hey man.
I have to say I am deeply impressed by your swiftness and your will to take responsibility! Amazing work! Keep on rocking! :)

**Comment by klazuka** [comment]
A lot of credit goes to @ajalt. He has done some amazing work on this project.

**Comment by DoctypeRosenthal** [comment]
And you are humble as well!! Great job mate! 👍👊

**Comment by klazuka** [comment]
@DoctypeRosenthal [version 2.2.3](https://github.com/klazuka/intellij-elm/releases/tag/v2.2.3) fixes the "has parse errors" restriction described above. Previously, if there were any parse errors in your function, record field completion wouldn't work. But not we do the best we can given the information we have. There are still some cases where it won't work (if you don't have a type annotation, or if there are syntax errors in the function parameter list itself), but this should cover a lot of the real-world cases.

The new version will show up in the JetBrains plugin repo soon, or you can download it now from the link above.

**Comment by DoctypeRosenthal** [comment]
That's awesome!

**Comment by mattiasw2** [comment]
Once you support find usage of record fields, I also assume you will be able to support rename of record fields? (I am really impressed by 3.0, installed into Android Studio 3.3.1, and could play around with my project directly.)

**Comment by klazuka** [comment]
Correct. 

Doing this right may be a bit tricky, though, due to the variety of ways in which records and fields can be used in Elm (structural subtyping, record extension, field accessor functions).

**Comment by mattiasw2** [comment]
Yes, this is the most complicated part of Elm's typing system. How complete is your implementation? Does it use the Elm compiler?

**Comment by klazuka** [comment]
We don't use the Elm compiler at all. The type system is fully implemented with the exception of unification of type variables in functions that **lack a type annotation**. So if you write something like:

```elm
foo x = x
quux = foo [1,2,3]
```

... we cannot infer the type of the expression `foo [1, 2, 3]`. But if you add a type annotation to foo (`foo : a -> a`), it will correctly infer the type as `List number`.

**Comment by ajalt** [comment]
#459 implemented this for all references to aliases and annotations within annotated functions. I don't think it's feasable to implement for unannotated functions.

**Comment by klazuka** [comment]
When I created this issue almost 3 years ago, I never fully expected that it would ever get implemented. Thank you @ajalt for making it happen. PR #697 was the last piece in the puzzle. 

🎉
