### ISSUE TITLE
How to use intellij-elm???

### ISSUE THREAD

**Issue by RobertBrown3** [klazuka/intellij-elm#101]
There does not appear to be any documentation on how to use this plugin. There is some kind of setup needed to create an elm project, but there is no documentation on it anywhere that I can find.

Without a decent user manual of some kind, this plugin is unusable. Someme please write some documentation!

**Comment by klazuka** [comment]
Everything should work more-or-less automatically. All you have to do is open a directory that contains your Elm project. After that, it will prompt you to tell it where the Elm compiler that you want to use is located. And then it will ask for your elm.json (0.19) or elm-package.json (0.18) file. 

Can you provide some more details about what you are trying to do?

**Comment by RobertBrown3** [comment]
I am trying to compile and run an elm project that has been properly set up.

I did create and open the directory that contains my project. I pointed it to the elm compiler (I am using 0.18), and I pointed it to the elm-package.json file.

The problem is that regardless of having a legitimate elm-package.json file (having generated it using elm-make), and in the process downloaded the dependencies (in my case, for now I just need the HTML package), in Intellij I am seeing reference errors in my elm file.

My elm file has some pretty basic test code:
`import HTML exposing (..)

main = 
   h1[] [ text "Hello, World" ]
`
The IDE is displaying "unresolved reference" errors for HTML and just about everything in main.

The elm-package.json file contains:
`{
    "version": "0.1.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/user/project.git",
    "license": "BSD3",
    "source-directories": [
        "."
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/core": "5.1.1 <= v < 6.0.0",
        "elm-lang/html": "2.0.0 <= v < 3.0.0"
    },
    "elm-version": "0.18.0 <= v < 0.19.0"
}
`
This, as I said, was generated when I created things using elm-make. It is in the same folder as the elm file.

So, things that you should document are:

1. How to create a proper elm project prior to creating the project in Intellij -- especially since your plugin does not provide the means of creating a proper elm project the way the Java and Groovy plugins do. Simply saying that the user should use elm-make should be sufficient (unless you would suggest using another means). It took me almost a day to figure out what I needed to do. A single sentence saying this would have saved me a lot of time.

2. The kind of project to create in Intellij in order to access the elm project. I guessed that the right project is an empty one.  Others may not guess that. Simply saying "create an empty project in the directory where you created the elm project" should be sufficient. 

3. How to make the IDE find the dependencies in the project so that elm code won't have the reference errors I have been seeing. I have not yet figured out a way to do this. I am presuming, however, that you were able to test this plugin using an elm application's dependencies. How did you get those dependencies included in your editor/compilations? How did you prevent the reference errors? Feel free to tell me this...

4. How to run and test the Elm project in Intellij, once you have done what is necessary in (3).

These are what I can think of offhand that would be useful to document. I will probably think of more things as I continue to use this plugin.

**Comment by klazuka** [comment]
Thanks for the feedback. I'll make some improvements to the readme.

As to your issue where everything is showing up as an unresolved reference, can you confirm that `elm-lang/core` and `elm-lang/html` are present in your `elm-stuff` directory? Is the elm-stuff directory part of the IntelliJ project? Have you marked it as an excluded source root?

**Comment by RobertBrown3** [comment]
I did look at the directory structure that was in the project. It looks like everything from core and html are there.
One thing I didn't check is the dependencies (it seems each one of these packages comes with source and an elm-package.json file). There appears to be a dependency in the html package that I am not seeing.

I'll keep you informed.

**Comment by RobertBrown3** [comment]
One last question:

Is there a configuration or setup for running/testing Elm programs from within Intellij? Or do we have to use the elm command line to compile to Javascript in order to test?

**Comment by klazuka** [comment]
Run the code from the command line. Either by using elm-make, or something like [elm-live](https://github.com/wking-io/elm-live) or [create-elm-app](https://github.com/halfzebra/create-elm-app), etc.

I personally use webpack-dev-server with hot-module-reloading and elm-webpack-loader.

**Comment by klazuka** [comment]
I don't think there's anything more left to do here. If you are still having trouble, please re-open the issue or start a new one.
