### ISSUE TITLE
Parameter binding references in nested case statements incorrectly resolve

### ISSUE THREAD

**Issue by ajalt** [klazuka/intellij-elm#106]
Names declared in previous case case branches should not resolve, but do. This only occurs if the case expression is nested.

![capture](https://user-images.githubusercontent.com/1109214/47736928-fa407480-dc2c-11e8-9533-8a8b6b7a64fe.PNG)

**Comment by klazuka** [comment]
this is the same scenario where I saw a crash: `java.lang.IllegalStateException: failed to bind pattern for expr of type VALUE_EXPR`. So maybe there are not very many of these that need to be fixed before releasing.

**Comment by ajalt** [comment]
Yes, that crash will happens if you have a reference to a value that's not visible in the current scope (which shouldn't be possible). It's why I noticed this bug.
