### ISSUE TITLE
Issues in Elm 18 codebase after updating the plugin to v2.0.0

### ISSUE THREAD

**Issue by Birowsky** [klazuka/intellij-elm#113]
<img width="452" alt="screen shot 2018-11-03 at 09 34 40" src="https://user-images.githubusercontent.com/3199950/47950891-af3e9e00-df59-11e8-89ff-94b2bb8b68c0.png">
<img width="726" alt="screen shot 2018-11-03 at 11 16 21" src="https://user-images.githubusercontent.com/3199950/47950913-f167df80-df59-11e8-9212-600382852f4a.png">

Let me know whatever additional info/context you need, I'll provide. In meantime, here's the elm-package.json

```
{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/gotaguy/frontend.git",
    "license": "BSD3",
    "source-directories": [
        "src/scripts"
    ],
    "exposed-modules": [],
    "native-modules": true,
    "dependencies": {
        "Gizra/elm-dictlist": "2.1.1 <= v < 3.0.0",
        "NoRedInk/elm-decode-pipeline": "3.0.0 <= v < 4.0.0",
        "danyx23/elm-mimetype": "3.0.1 <= v < 4.0.0",
        "debois/elm-dom": "1.2.3 <= v < 2.0.0",
        "dillonkearns/graphqelm": "10.0.0 <= v < 11.0.0",
        "elm-community/dict-extra": "1.3.1 <= v < 2.0.0",
        "elm-community/elm-datepicker": "5.0.1 <= v < 6.0.0",
      "elm-community/html-extra": "2.2.0 <= v < 3.0.0",
        "elm-community/json-extra": "2.1.0 <= v < 3.0.0",
        "elm-community/list-extra": "7.0.1 <= v < 8.0.0",
        "elm-community/maybe-extra": "3.1.0 <= v < 4.0.0",
        "elm-community/result-extra": "2.2.0 <= v < 3.0.0",
      "elm-community/string-extra": "1.5.0 <= v < 2.0.0",
        "elm-lang/core": "5.0.0 <= v < 6.0.0",
        "elm-lang/dom": "1.1.1 <= v < 2.0.0",
        "elm-lang/geolocation": "1.0.2 <= v < 2.0.0",
        "elm-lang/html": "2.0.0 <= v < 3.0.0",
        "elm-lang/http": "1.0.0 <= v < 2.0.0",
        "elm-lang/keyboard": "1.0.1 <= v < 2.0.0",
        "elm-lang/navigation": "2.0.1 <= v < 3.0.0",
        "elm-lang/svg": "2.0.0 <= v < 3.0.0",
        "elm-lang/window": "1.0.1 <= v < 2.0.0",
        "justinmimbs/elm-date-extra": "2.0.3 <= v < 3.0.0",
        "labzero/elm-google-geocoding": "4.0.1 <= v < 4.1.0",
        "mgold/elm-date-format": "1.1.7 <= v < 2.0.0",
        "myrho/elm-round": "1.0.2 <= v < 2.0.0",
        "simonh1000/elm-jwt": "5.3.0 <= v < 6.0.0",
        "simonh1000/file-reader": "1.2.0 <= v < 2.0.0",
        "wernerdegroot/listzipper": "3.0.0 <= v < 4.0.0"
    },
    "elm-version": "0.18.0 <= v < 0.19.0"
}
```

**Comment by Birowsky** [comment]
> The second one may or may not be a bug

It compiles ; )

>  Try to reduce it down to the smallest example possible

```
whereDidItAllGoWrong : Bla -> String
whereDidItAllGoWrong bla =
    bla.apiUrl --todo: drama here


type alias Bla =
    Bla2 Bla3


type alias Bla2 a =
    { a | newProperty : String }


type alias Bla3 =
    { apiUrl : String }
```

There are many other type mismatching errors around the app. Example:

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/3199950/47955091-0b71e400-df93-11e8-9ea1-f3170411c5b9.png">

Should I report them as well? Feel free to ask for whatever context you need!

**Comment by klazuka** [comment]
@Birowsky that's great, thank you. If you don't mind, can you also post a small example of the error shown in the newest screenshot?

@ajalt looks like something is wrong when inferring fields on extended records.

**Comment by Birowsky** [comment]
I couldn't figure it out for the one on the screenshot, but here's another one:

```
youDontKnowMeLikeIKnowYou =
    case justLeave of
        Just [] ->
            "i'll never see you again, will I"

        Nothing ->
            "nope"


justLeave : Maybe (List { a | whatever : String })
justLeave =
    Nothing
```

Code haiku should be a thing.

<img width="398" alt="image" src="https://user-images.githubusercontent.com/3199950/47955332-de273500-df96-11e8-8a6c-d2cb8f401311.png">

**Comment by ajalt** [comment]
@Birowsky Thanks for the report! If you have any more examples, it would be very helpful if you could post them in a new issue. You don't need to worry about minimizing them too much; as long as it's enough to reproduce an error, that's great. Even a link to an entire project would be fine if you have one that's public.

**Comment by Birowsky** [comment]
Man I'm glad you guys are dedicated to the plugin!

**Comment by Birowsky** [comment]
This is still broken in v2.0.1

```
whereDidItAllGoWrong : Bla -> String
whereDidItAllGoWrong bla =
    bla.apiUrl --todo: drama here


type alias Bla =
    Bla2 Bla3


type alias Bla2 a =
    { a | newProperty : String }


type alias Bla3 =
    { apiUrl : String }
```

**Comment by klazuka** [comment]
I know. AJ fixed it after I published the 2.0.1 hotfix. It will be in the next release.

**Comment by Birowsky** [comment]
@klazuka is the next release published? I haven't gotten any updates yet.

**Comment by klazuka** [comment]
Not yet. I was waiting to see if there were any other major bugs. I will do the release today.

**Comment by Birowsky** [comment]
Thank you bery much.
