### ISSUE TITLE
Name shadowing should not be reported as an error in Elm 0.18 projects

### ISSUE THREAD

**Issue by klazuka** [klazuka/intellij-elm#114]
@birowsky reported that name shadowing is marked as an error in Elm 0.18, but it should be allowed.

<img width="452" alt="47950891-af3e9e00-df59-11e8-89ff-94b2bb8b68c0" src="https://user-images.githubusercontent.com/84525/47954685-3a179c80-df4a-11e8-97b1-2e44b6d28978.png">

We need to silence the diagnostic for files belonging to Elm 0.18 projects.

**Comment by klazuka** [comment]
The fix for the name shadowing error can be installed from here: https://github.com/klazuka/intellij-elm/releases/tag/v2.0.1
Otherwise, it will be available via the normal JetBrains distribution mechanism on Monday or Tuesday.

**Comment by Birowsky** [comment]
No idea how to install plugin from source. I'll wait for the release : )

**Comment by muelli** [comment]
FWIW: It would help me big time if the iDE showed a warning or something that the code is not forward compatible.
I am porting a medium sized app to 0.19 and finding and resolving shadowed variables costs lots of time. If the plugin showed an (optional?) warning, it'd be easier to not re-introduce those.

**Comment by klazuka** [comment]
That would be cool, but I don't have enough free time to develop new features just for 0.18
