### ISSUE TITLE
Can't find references to elm-explorations/test when source-directories is ["."]

### ISSUE THREAD

**Issue by mickeyvip** [klazuka/intellij-elm#119]
All the imports from `elm-explorations/test` are marked as `unresolved reference ''`.

Might it be because of the `elm-explorations/test` is under `test-dependencies` in `elm.json`?

`External Libraries` does have it:

![image](https://user-images.githubusercontent.com/220427/48254121-c70e9a00-e411-11e8-9575-3d19a449e388.png)

Plugin version `2.0.1`

Anyhow - thank you so much for the plugin and taking time to develop it further!

**Comment by klazuka** [comment]
I did make a change in 2.0.1 related to how `test-dependencies` resolve, but your use-case should still work. I tested it on a 0.19 application a 0.19 package project, and in both cases, it resolved the dependency fine.

Can you please post the contents of your `elm.json` file?

Also, please verify that the expected `elm.json` file is attached. On the right border of the IntelliJ window there is a button for the Elm tool window. Open that up. It should list the path to one or more `elm.json` files. Verify that the path is as-expected. You can try pressing the Refresh button here to see if that fixes things.

Let me know what you find, as it is quite possible that I broke something.

**Comment by mickeyvip** [comment]
Hi again.

I just created a project from scratch and added a test for example. All is working fine.

From what I see - it works for the new project because `source-directories` is set to `[ "src" ]`.

When I set `source-directories`  to `[ "src" ]` in the downloaded project - there are no errors.

Can it be that the search path is hardcoded to `src`?

**Comment by klazuka** [comment]
The only time it should require that source-directories is ‘src’ is for package projects (because that’s how Elm 0.19 works). But maybe I screwed something up. I will try to look at it this weekend. Thanks for narrowing the problem down.

**Comment by mickeyvip** [comment]
Those projects do look like a package projects - no `main`.

Attached a project from exercism.io for you as an example.
[sublist.zip](https://github.com/klazuka/intellij-elm/files/2568169/sublist.zip)

**Comment by klazuka** [comment]
Thanks. I can reproduce it using your example. For now, the workaround is to use `"src"` as your source-directory instead of `"."` I will fix it in a subsequent release.

**Comment by mickeyvip** [comment]
Thanks!

That's what I am doing

- create a `src` folder
- copy the main file there
- update `source-directories` to `[ "src" ]`

**Comment by klazuka** [comment]
The fix is out now in a pre-release build: https://github.com/klazuka/intellij-elm/releases/tag/v2.0.3-rc1

That link has an attached zip file which contains the compiled plugin. It’s pretty easy to install. 

So if you get a chance, give it a try and let me know if you run into any problems. Assuming everything is fine, I will submit it to JetBrains on Monday for publishing.

**Comment by mickeyvip** [comment]
Hi.

Just updated the plugin with the `RC`.

- new project from Excercism (where sources are in the root and `source-directories` is `[ "." ]`) - OK
- changing `source-directories` from `[ "." ]` to `[".", "src"]` - OK 
- changing `source-directories` from to `["src"]`, shows errors only for the file located in the root in tests and for the Elm dependencies in the file located in the root - seems to be OK: 
![image](https://user-images.githubusercontent.com/220427/48686697-0c775800-ebc6-11e8-93d9-ec996fa4364f.png)

![image](https://user-images.githubusercontent.com/220427/48686708-1a2cdd80-ebc6-11e8-814e-e161c63e6e68.png)

- moving the file located in the root to the `src` folder, while `source-directories` is set to `["src"]` - OK
- changing `source-directories` from `[ "." ]` to `[".", "src"]` after the last step - OK 
- creating  a new file in the root after the last step, so we have 1 file in the root and another in the `src` folder - OK 

So I would say it is working great.

Thank you!

P.S. I love the new "exposed" icon!
![image](https://user-images.githubusercontent.com/220427/48686818-bb1b9880-ebc6-11e8-9f2a-97148023decf.png)
