### ISSUE TITLE
Doesn't respect $ELM_HOME envvar

### ISSUE THREAD

**Issue by drathier** [klazuka/intellij-elm#121]
Assumes `$ELM_HOME` to equal its default; `~/.elm`.

**Comment by klazuka** [comment]
It should, but perhaps the environment variable is not getting passed into IntelliJ. Or it could very well be that my code is broken. 


Which OS are you using? How are you defining the environment variable? And how are you launching IntelliJ?

**Comment by drathier** [comment]
Fair enough, must've missed it then. How do you expect me to pass in the envvar?

**Comment by klazuka** [comment]
Which OS are you using?

I found [this comment](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206591465/comments/205979869) by an IntelliJ developer that might be helpful. It's specific to macOS, but you should be able to apply it similarly to your platform.

Let me know what you find out, and I will add it to the README.

**Comment by drathier** [comment]
Should work as expected then. I had an uncommon use-case where I needed two projects open at the same time to have two different `$ELM_HOME`s.
