### ISSUE TITLE
Extensible records / record types are failing in Elm 18

### ISSUE THREAD

**Issue by Birowsky** [klazuka/intellij-elm#122]
Sup fellas, here's an example:

<img width="389" alt="image" src="https://user-images.githubusercontent.com/3199950/48300780-8aab6e80-e4e3-11e8-8d88-dd11b87d2262.png">

```

iFail : Bla1 Bla2 -> String
iFail { bla2 } =
    "    ^ here I fail"


type alias Bla1 a =
    { a
        | bla : Int
    }


type alias Bla2 =
    { bla2 : Int }
```

**Comment by klazuka** [comment]
cc @ajalt

**Comment by klazuka** [comment]
The fix is out now in a pre-release build: https://github.com/klazuka/intellij-elm/releases/tag/v2.0.3-rc1

That link has an attached zip file which contains the compiled plugin. It’s pretty easy to install. 

So if you get a chance, give it a try and let me know if you run into any problems. Assuming everything is fine, I will submit it to JetBrains on Monday for publishing.

**Comment by Birowsky** [comment]
Sorry for being late, I had to prioritize some stuff.

I tried the update, and, so, there still are quite a few problems. But I'm not sure how to hunt these down to minimal cases. 

Let's see if the errors themselves help you out? Maybe you'll find a pattern?


<img width="660" alt="screen shot 2018-11-19 at 19 20 05" src="https://user-images.githubusercontent.com/3199950/48726717-86dcc200-ec30-11e8-8212-43a6dde8fd97.png">
<img width="1320" alt="screen shot 2018-11-19 at 19 19 56" src="https://user-images.githubusercontent.com/3199950/48726718-87755880-ec30-11e8-84c6-2bbe28a864a8.png">
<img width="514" alt="screen shot 2018-11-19 at 19 19 15" src="https://user-images.githubusercontent.com/3199950/48726720-87755880-ec30-11e8-9afb-49d774aa87e5.png">
<img width="442" alt="screen shot 2018-11-19 at 19 19 03" src="https://user-images.githubusercontent.com/3199950/48726722-880def00-ec30-11e8-8245-4f802d564f78.png">
<img width="484" alt="screen shot 2018-11-19 at 19 18 54" src="https://user-images.githubusercontent.com/3199950/48726723-880def00-ec30-11e8-8cc4-5bea410f7551.png">
<img width="450" alt="screen shot 2018-11-19 at 19 18 43" src="https://user-images.githubusercontent.com/3199950/48726724-880def00-ec30-11e8-9e23-4d0a4ca5cebd.png">
<img width="448" alt="screen shot 2018-11-19 at 19 18 09" src="https://user-images.githubusercontent.com/3199950/48726726-88a68580-ec30-11e8-92c6-c1921728a23a.png">

**Comment by Birowsky** [comment]
I found another bug: Find Usages in All Places is not showing all results with some symbols.

Could you confirm that you got these messages? Do you need me to create separate issues?

**Comment by klazuka** [comment]
@birowsky can you create a separate issue for the Find Usages bug?

**Comment by klazuka** [comment]
I’ll reopen this issue to track the type checker bug on records.

**Comment by ajalt** [comment]
@Birowsky I haven't been able to reproduce the new report based on your pictures, so if you're able to post a program the exhibits the error (minimized or not), then I'd be grateful.

**Comment by Birowsky** [comment]
Sure thing mate

**Comment by klazuka** [comment]
@Birowsky version [2.2.1](https://github.com/klazuka/intellij-elm/releases/tag/v2.2.1) has some fixes related to record extension. After you give it a try, please follow-up on this issue whether the problem is fixed or not.

**Comment by Birowsky** [comment]
@klazuka Just checked, unfortunately, I still have all the errors in the screenshots. If I manage to isolate any of these, I'll let you know.
