### ISSUE TITLE
Elm imports are not working with Intellij Ultimate latest (2018.3 Nov 21) version.

### ISSUE THREAD

**Issue by ederinbay** [klazuka/intellij-elm#137]
When I installed the latest version of Intellij Ultimate 2018.3 Nov 21 version,  imports of the elm file were broken. I check Elm plugin (2.0.2) and elm.json file but everything is normal. I install previous version (Ultimate 2.6) and everything works now.

**Comment by klazuka** [comment]
I've been using 2018.3 without a problem, but I wouldn't be surprised if there are some new bugs.

Are you sure that you had an `elm.json` file "attached" in IntelliJ? There's an Elm tool window on the right-hand side which shows the list of attached `elm.json` files. If it's not there, then try attaching again.

Also, which OS are you using?

**Comment by ederinbay** [comment]
Yes, it is attached. I use macOS Mojave.

**Comment by klazuka** [comment]
And what happens if you press the "Refresh" button in the Elm tool window? Are any errors displayed?

Do you see any Elm packages listed in the "External Libraries" section of IntelliJ's project view?

**Comment by ederinbay** [comment]
There is no error message.         These are in elm.json file and the same are in external libraries.
        "elm/browser": "1.0.0 <= v < 2.0.0",
        "elm/core": "1.0.0 <= v < 2.0.0",
        "elm/html": "1.0.0 <= v < 2.0.0",
        "elm/http": "1.0.0 <= v < 2.0.0",
        "elm/json": "1.0.0 <= v < 2.0.0",
        "rundis/elm-bootstrap": "5.0.0 <= v < 6.0.0"

**Comment by klazuka** [comment]
hmm. Looks like the project loaded fine.

In the "External Libraries" section, do you actually see files and directories underneath each package or are they empty?

Assuming "External Libraries" looks good, then maybe it's a caching problem. Have you tried restarting IntelliJ? If that doesn't work, you can try clearing IntelliJ's caches. On the menu bar: `File -> Invalidate Caches / Restart...`

**Comment by ederinbay** [comment]
I restarted and revert the latest changes of the program. Program works now but more than 500 error messages are still shown and all of them import related. But I can use my file now. Is that a little bit weird?

**Comment by klazuka** [comment]
It does sound weird. Can you post a screenshot of your expanded “External Libraries” section?

**Comment by ederinbay** [comment]
I invalidate caches and restart. At first it seems working but after indexing, all error messages appear again. Here it is:

![image](https://user-images.githubusercontent.com/42933395/48961501-4ef9b580-ef75-11e8-9c0e-c723bd69cdd0.png)

**Comment by klazuka** [comment]
And I’m guessing that the 1.0.0 directories are not empty? You can actually find .elm files in there and that you can open them. You just need to check this for one of the imports that are failing. Thanks.

**Comment by ederinbay** [comment]
This is an example of elm.browser. I opened Browser.elm and there is an error with import url.
For now I will use previous version I think.
Thanks for your interest and quick reply.

<img width="326" alt="screenshot 2018-11-23 at 23 27 21" src="https://user-images.githubusercontent.com/42933395/48961802-d9dbaf80-ef77-11e8-8fd2-15ab7c192844.png">

**Comment by klazuka** [comment]
Ok. Sorry I couldn't be more helpful. Let me know if you continue to have problems down the road and I will talk you through the process of getting debug-level logs from you.

**Comment by ederinbay** [comment]
It is appreciated.Thanks...

**Comment by ederinbay** [comment]
Hi, problem solved. It is not related with Intellij. When I update it, it automatically use the newer version of elm plugin. (Mine plugin was 2.0.2) Something was wrong with my elm.json file I think. It somehow works with 2.0.2 but not newer versions.  After making some changes on it, it begins to work again. Thanks again for your support...
