### ISSUE TITLE
"Find Usages in All Places" is not showing all results for some symbols

### ISSUE THREAD

**Issue by Birowsky** [klazuka/intellij-elm#139]
Promoting the comment from here: https://github.com/klazuka/intellij-elm/issues/122#issuecomment-441129280

In meantime I have forgotten about the symbols in my project that caused this. I'll update this when I face them again.

**Comment by klazuka** [comment]
Find Usages should work for pretty much everything in your Elm programs *except record fields*. Implementing this correctly requires type inference, and we still have more work to do to finish that up.

I'm going to close this ticket, but please feel free to re-open it if you find something other than record fields that should work with Find Usages but doesn't.

**Comment by Birowsky** [comment]
Ah no. It was an ADT value (union type value). But as I said, when it happens again, I’ll make sure to note it down.
