### ISSUE TITLE
Resolving reference does not auto complete for unimported modules

### ISSUE THREAD

**Issue by mordrax** [klazuka/intellij-elm#146]
If I'm in module A and I start typing, `ModuleB.someFunction` there are a few scenarios:

1. If ModuleB is already imported, I get a list of options to auto complete someFunction.
2. If ModuleB is not imported, there is no auto complete. 

Further to this, when you try to resolve the function in scenario 2:
2a. If the function `someFunction` is valid, ie exported by ModuleB, it will add the import line (Alt+Enter, Enter)
2b. If the function has a typo or is misspelt, it does not find the ModuleB or function

The end result is that you have to know beforehand the exact module and function name you want to import for auto complete/reference to work which defeats the purpose of it.

v 1.3.3
Happens on mac, ubuntu
Elm 0.19

**Comment by klazuka** [comment]
I know. This is just one of those things that haven’t been implemented yet. It’s on my short-list of tasks that give a lot of value for the amount of work required to implement. 

So hopefully soon-ish.

**Comment by mordrax** [comment]
icic, carry on the Good Works then. I thought i'd remember it was in a previous release, but I think my memory's at fault here.

**Comment by klazuka** [comment]
@mordrax this feature is out now in version 2.1.1
