### ISSUE TITLE
Add/remove a value/function/type from the module's exposing list

### ISSUE THREAD

**Issue by klazuka** [klazuka/intellij-elm#147]
There are 2 steps to this:
1. add an intention action on top-level things to add it to the module's exposing list
2. add an action to the "exposed" gutter icon to remove it from the exposing list

One complication is that messing around with the exposing list is kind of a pain because you have to manually deal with the PsiWhitespace elements. It'd be nice if we had a better way to do local code formatting for whitespace.

As for (2), I found the following tip on the IntelliJ dev forums:
> The renderer returned by LineMarkerInfo instances you generate should define popup menu actions (com.intellij.openapi.editor.markup.GutterIconRenderer#getPopupMenuActions). You can look at RunLineMarkerProvider, as an example (that's what shows popup in your screenshot).

**Comment by klazuka** [comment]
@ajalt i know you were interested in working on this. Let me know if you start working on it so that we don't overlap.

**Comment by rdelgatte** [comment]
I like this idea mainly when dealing with unit tests. 
Actually, when creating new test functions, I have to add it manually to the test module's exposing list  and I would have liked a way to do it more easily / quickly. Is there a workaround for doing that?

**Comment by klazuka** [comment]
No workaround, but I’m currently working on adding this feature. So it won’t be long.

**Comment by klazuka** [comment]
I guess the "workaround" is to define and expose a single test suite function [as shown here](https://github.com/elm-explorations/test#quick-start). Then all you have to do is call your test from the suite function. (But that kinda has the same problem as the file grows—lots of scrolling up and down).

**Comment by rdelgatte** [comment]
Thank you for your feedback, it does work well with described test suite as far as I played with but I think it would be nice to get this feature anyway (when tests files grows more and more) so I'm looking forward to use it!
