### ISSUE TITLE
No support for multiple elm projects per intellij project.

### ISSUE THREAD

**Issue by francescortiz** [klazuka/intellij-elm#15]
I have to elm projects in the same web project: one for frontend and one for backend. Each project has its elm-package.json file that encloses each project's source code, but references are always searched within only one of the projects, instead of being searched in their own project.

**Comment by klazuka** [comment]
This is a known limitation of how the plugin is implemented currently. It does not (yet) use the `elm-package.json` files so it has no idea about separate source roots. Besides the use-case you provided, this also affects things like `elm-test` which also create their own, separate Elm source root.

Not sure when I will get around to fixing this.

**Comment by francescortiz** [comment]
I came out with a workaround. What I do is to mark any other source root except the one that I am working on as excluded.
