### ISSUE TITLE
performance: slow file I/O when determining whether a module is visible to an ElmProject

### ISSUE THREAD

**Issue by klazuka** [klazuka/intellij-elm#157]
`Files.isSameFile` and `Files.exists` are taking a lot of time when running the unresolved reference annotator (which basically happens on every key-press). These get called as part of filtering all known Elm modules based on what should be visible to the calling Elm file (based on the source-directories and dependencies in `elm.json`)

In the following CPU profiler snapshot, all I did was type some characters inside an Elm string literal in a module that has ~50 imports.

<img width="1243" alt="screen shot 2018-12-03 at 11 48 49 am" src="https://user-images.githubusercontent.com/84525/49397825-8db80a00-f6f1-11e8-928c-cdf9530d2ffd.png">

**Comment by raphaelpereira** [comment]
I think I have this problem. I monitor processes and I noticed that every key I press the following command is run:

node /usr/local/bin/elm --version

And it gets the editor EXTREMELLY slow!

**Comment by klazuka** [comment]
That's a separate problem that I had overlooked. I'll add some caching for it in the next release.

**Comment by raphaelpereira** [comment]
Ok, I will open another issue then

**Comment by raphaelpereira** [comment]
I managed to build the plugin using master version and it worked! Now I can use the IDE without any lag. Thank you very much!

**Comment by klazuka** [comment]
Cool. Please let me know if you run into any other problems.
