### ISSUE TITLE
Elm version not found

### ISSUE THREAD

**Issue by PascalLeMerrer** [klazuka/intellij-elm#159]
The plugin configuration seems broken on my machine (Mac OSX High Sierra, Intellij Ultime 2018.3).

Although the path to the directory containing the elm executable is correct, it displays "not available" in the "elm version" field.

Version of the plugin: 2.1.0

**Comment by klazuka** [comment]
Can you paste here the output when you run `elm --version` from the command line? If you have multiple copies of Elm on your system, please make sure that you get the version from the binary that is located at the path you specified in the plugin settings. Thanks!

**Comment by PascalLeMerrer** [comment]
Executing `elm --version` displays the path of the elm executable:

`/Users/pascal/.npm-packages/lib/node_modules/elm/unpacked_bin/elm`
0.19.0`

While `which elm` points to `/Users/pascal/.npm-packages/lib/node_modules/elm/bin/elm`. This is a node  script which invokes the  executable I mentioned above.
Until then I entered in the configuration pane the path of the node script, and it caused the issue.
Entering the path of the directory containing the executable solves it.

Thanks for your help.
