### ISSUE TITLE
Provide an intention action to populate the branches in a `case` expression

### ISSUE THREAD

**Issue by rosensama** [klazuka/intellij-elm#160]
One little gadget from elmjutsu in Atom that I like best is that if you type `case var of` in a function it can resolve the type and the various required cases and generates a skeleton of all the cases.

I'm suggesting (begging for?) it to be added here.  Say I have:

```elm
type Msg
    = Foo String
    | Bar 
```

Then I setup:

```elm
update : Msg -> Model -> ( Model, Cmd Msg)
update msg model = 
    case msg of
```

Once I complete `of` I automagically get
```elm
update : Msg -> Model -> ( Model, Cmd Msg)
update msg model = 
    case msg of
        Foo str -> -- `str` is part of the autogeneration

        Bar ->
```
Makes me smile every time.  

Thanks for the great tool and thanks for reading this far.

**Comment by klazuka** [comment]
We most certainly will implement this. Previously it was blocked by not knowing the types of things, but now the type system is useful enough that we could do this. I will put this on my short-list of things to do.

**Comment by klazuka** [comment]
@rosensama this feature is out now in version 2.1.1

**Comment by klazuka** [comment]
I think IntelliJ calls it “Smart statement completion”. Press ctrl-shift-enter (or on a Mac, cmd-shift-enter)
