### ISSUE TITLE
Expose 'create function decl from type annotation' as an Action so that it can be bound in the keymap

### ISSUE THREAD

**Issue by rosensama** [klazuka/intellij-elm#161]
The feature to create the function declaration with variable names is very helpful.  Is this exposed as an action that I could map a keystroke to?

Thanks for the plugin.

**Comment by klazuka** [comment]
No, it's not, but it seems like a reasonable thing to do. You're welcome to contribute it if you like, otherwise I will get around to it down the road. If you do want to get involved, I would be happy to provide whatever guidance is needed.

**Comment by rosensama** [comment]
Let me do a little reading to see if I could do this.   Your change of description gives me the research entry points, I think.

**Comment by klazuka** [comment]
I haven't implemented this exactly before, but here is some rough guidance.

The code that generates the Elm function based on the type annotation is `ElmMakeDeclarationIntentionAction`. Here are some IntelliJ docs regarding intentions:

- http://www.jetbrains.org/intellij/sdk/docs/tutorials/code_intentions.html
- http://www.jetbrains.org/intellij/sdk/docs/reference_guide/custom_language_support/code_inspections_and_intentions.html

As far as I know, the way to get some plugin functionality to show up in the menus and be able to be bound to a keyboard shortcut in the keymap is to implement `AnAction` and register it in the plugin's XML file. Here are some docs on the action system:
- https://www.jetbrains.org/intellij/sdk/docs/tutorials/action_system/working_with_custom_actions.html
- https://www.jetbrains.org/intellij/sdk/docs/basics/action_system.html

IntelliJ's intentions and actions always confuse me, and so I just looked into it. Peter Gromov has a pretty good explanation: https://intellij-support.jetbrains.com/hc/en-us/community/posts/206765705/comments/206121645

The question that I don't know the answer to is how to glue together intention actions (which is what `ElmMakeDeclarationIntentionAction` is) and regular actions (which is necessary for keyboard shortcuts).

Maybe the solution is as simple as creating a class which (1) implements `AnAction` and (2) delegates to `ElmMakeDeclarationIntentionAction` to do the work (or factor out the functionality).

**Comment by klazuka** [comment]
@rosensama it looks like @ajalt figured out an even better way to do this. He's working on automatically generating the branches in a `case foo of` expression, and he used a smart-enter processor to make it work. This way you can use an existing keyboard shortcut that's fairly well-known. 

See `ElmSmartEnterProcessor` in his PR: https://github.com/klazuka/intellij-elm/pull/168/files

So I would hold off on any work here until that PR lands and then build the feature on top of this new `ElmSmartEnterProcessor`.

**Comment by rosensama** [comment]
I think this already works based on the work that you said was coming.  I'm on OS X at the moment and if the light bulb is displayed I can hit `alt + return` to get the drop down and `return` again to trigger the action.  

Guess the last step would be to do work to expose it so it could be bound via Keymaps?

**Comment by klazuka** [comment]
Yes, right now you can do it entirely from the keyboard as you described. AJ has a branch which will allow it to also be triggered via smart statement completion (ctrl-shift-enter). 

We will continue to provide both options as the former is more discoverable whereas the latter is more efficient.

**Comment by klazuka** [comment]
Now that #205 has landed, it should be easy to make Type Annotations participate in the "complete current statement" system by generating the function body skeleton.

**Comment by klazuka** [comment]
Well, I tried implementing this, but it didn't work out. The "complete current statement" (SmartEnterProcessor) does not like the Live Template system which we use for stepping through the default parameter names. We could conditionally not use the Live Template system, but it's awfully useful in this case because at least half of the time you're going to want to change the default parameter names.

I think the best thing to do here is stick with the existing `alt + return` workflow for invoking this functionality. It's only one extra keypress, and it keeps things consistent.
