### ISSUE TITLE
Imported functions fail to shadow Basics

### ISSUE THREAD

**Issue by ajalt** [klazuka/intellij-elm#162]
The plugin incorrectly resolves references to functions that should shadow names from the `Basics` module.

![annotation 2018-12-13 151450](https://user-images.githubusercontent.com/1109214/49973502-3a606b80-feea-11e8-9127-c817a69bc3f3.jpg)

In the above example, the `and` function should resolve to the function defined in `Bitwise`, but it instead resolves to the one defined in `Basics`.

**Comment by romariolopezc** [comment]
Having this error 👍
