### ISSUE TITLE
List destructuring shows error for 2 items

### ISSUE THREAD

**Issue by DoctypeRosenthal** [klazuka/intellij-elm#164]
This is the problem 
![image](https://user-images.githubusercontent.com/12626798/50053076-ded2ef80-012e-11e9-940b-a8ab5d0c3287.png)

The type checker thinks that `height` is the list's tail instead of the second item in a list of 2 items. 
I can compile without problem and the program executes as expected.

When I try to alter the destructuring into

![image](https://user-images.githubusercontent.com/12626798/50053092-222d5e00-012f-11e9-9796-dd446ff1f2d6.png)

It doesn't display an error anymore but the program behaves not as expected.

The parseWithDefault function 
![image](https://user-images.githubusercontent.com/12626798/50053139-ca432700-012f-11e9-8a92-31d53ee54d31.png)

What can I do?
Thank you!

**Comment by klazuka** [comment]
Looks like a bug in type inference in the pattern matching code. Cc @ajalt
