### ISSUE TITLE
Support Ctrl/Cmd+P (Parameter info within function call)

### ISSUE THREAD

**Issue by boxed** [klazuka/intellij-elm#17]
This keyboard shortcut is very nice when you have a function with more than say 2 arguments :P

**Comment by klazuka** [comment]
The plugin doesn't (yet) know about the types of things, but I think this would be easy to implement in the common case where the function has a type annotation by just displaying the type annotation and assuming that it is correct.

This would probably be pretty easy for a contributor to work on. If anyone wants to give it a go, I would be happy to provide more guidance.

**Comment by klazuka** [comment]
I'm pretty sure that the IntelliJ hook is to subclass [ParameterInfoHandler](https://upsource.jetbrains.com/idea-ce/file/idea-ce-d00d8b4ae3ed33097972b8a4286b336bf4ffcfab/platform/lang-api/src/com/intellij/lang/parameterInfo/ParameterInfoHandler.java) and then register your subclass under the `codeInsight.parameterInfo` extension point in the plugin's XML manifest.
