### ISSUE TITLE
Module in "tests" directory cannot be imported by other files in "tests"

### ISSUE THREAD

**Issue by tmohme** [klazuka/intellij-elm#189]
With elm 0.19.0 I've modularized my code like this:

```
src/ModuleA
src/ModuleB -- imports ModuleA
tests/ModuleATest -- imports ModuleA, ModuleASupport
tests/ModuleASupport
tests/ModuleBTest -- imports ModuleB, ModuleA, ModuleASupport
```

On the command-line, both `elm make` and `elm-test` run without problems.
In IntelliJ (2018.3.2 CE) with the 'Elm' plugin (v2.1.1) and the 'Elm External Tools' plugin (v2.0.1), all the references to functions in `tests/ModuleASupport` are marked as "Unresolved reference" though.

I'm not sure whether this is an issue with the 'Elm' plugin, or with the 'Elm External Tools' plugin.  
I decided to post this issue here, because the behavior doesn't change if I disable the 'Elm External Tools' plugin.

As my project structure is valid for both `elm make` and `elm-test`, I hope there is a way to also make the 'Elm' plugin understand it.

**Comment by klazuka** [comment]
This is probably a bug in my code. Would you mind posting your elm.json file?

Also, is it ONLY the ModuleASupport file which fails to resolve? Is the plugin able to resolve the references to things like Expect and Test provided by elm-test?

**Comment by tmohme** [comment]
Yes, it is *only* the functions from ModuleASupport that don't resolve.  
Everything else (Expect, Test, ModuleA, ModuleB, ...) works fine.

elm.json:
```
{
    "type": "application",
    "source-directories": [
        "src/main/elm"
    ],
    "elm-version": "0.19.0",
    "dependencies": {
        "direct": {
            "elm/browser": "1.0.1",
            "elm/core": "1.0.2",
            "elm/html": "1.0.0",
            "elm/json": "1.1.2",
            "elm-community/maybe-extra": "5.0.0"
        },
        "indirect": {
            "elm/time": "1.0.0",
            "elm/url": "1.0.0",
            "elm/virtual-dom": "1.0.2"
        }
    },
    "test-dependencies": {
        "direct": {
            "elm-explorations/test": "1.2.0",
            "elm-community/random-extra": "3.0.0"
        },
        "indirect": {
            "elm/random": "1.0.0"
        }
    }
}
```
You can view the whole project on [Github](https://github.com/tmohme/scoreboard/releases/tag/intellij-elm-issue-189).  
To build it run `./gradlew build`.

**Comment by klazuka** [comment]
Thanks. I’ll look into getting a fix in for the next release (sometime this week)

**Comment by klazuka** [comment]
I was able to reproduce the bug using your example code. Thanks! The problem is that the plugin is not treating the `tests` directory as a src-directory when in a testing context.

The fix is to detect whether we are importing from `tests` and, if so, add `tests` to the list of source-directories. It should be pretty easy for me to fix, but I want to improve a few other things related to test dependencies when I'm in there.
