### ISSUE TITLE
performance: elm --version is called on every keystroke

### ISSUE THREAD

**Issue by raphaelpereira** [klazuka/intellij-elm#200]
I monitor processes and I noticed that every key I press the following command is run:

node /usr/local/bin/elm --version

And it gets the editor EXTREMELLY slow!

**Comment by klazuka** [comment]
@raphaelpereira using `fs_usage` on macOS, I only see the Elm compiler version being queried when switching between Elm files (which itself is probably too often, but that's a separate problem).

Which OS are you on? Which version of IntelliJ are you running? Are you still seeing the performance problem?

**Comment by raphaelpereira** [comment]
Another fact is that it happens when I make any edition on any file type, as long as there is a single Elm file opened, the command is run on every keystroke (I suppose actually is on every file save inside IDE). Just close all Elm file and the command is not run anymore.

**Comment by raphaelpereira** [comment]
Actually this was the issue I was having and with the master compilation as of now I have no more lagging

**Comment by frou** [comment]
@raphaelpereira Does this Elm plugin work as fully in *GoLand* as it would in *WebStorm*? I'm unfamiliar with JetBrains products and the taxonomy of all their offerings is rather confusing!

**Comment by klazuka** [comment]
@frou In principle it should work well in all JetBrains IDEs. But I only test it in IntelliJ IDEA (my normal development env) and WebStorm.

**Comment by raphaelpereira** [comment]
@frou it seems so. I have only used it on GoLand and it works as expected (now with this patch applied)

**Comment by frou** [comment]
@klazuka @raphaelpereira Thank you. I've started on writing an Elm code completion daemon to be puppeteered by Sublime Text, but seeing the project here with all the advanced features is making me reconsider whether that's worth the effort!

**Comment by klazuka** [comment]
@frou it has been more work than I expected. I've been working on it pretty heavily for over a year now, and there's still some big things remaining (inline function, extract function, rename record fields).

If you're interested in learning Kotlin, contributions to this project would be welcome 😄

**Comment by frou** [comment]
You've definitely picked a more appropriate platform. My thing would most likely be brittle, trying to do things ad hoc and out-of-process.

Anyway, sorry for the offtopic noise on this issue. I will most likely become a user of `intellij-elm` soon!
