### ISSUE TITLE
Aliasing 'Random.Extra' as 'Random' can result in unresolved references

### ISSUE THREAD

**Issue by mickeyvip** [klazuka/intellij-elm#21]
Thank you for the plugin.

In Webstorm, whenever I have `as someAlias`, it shows an error:

![image](https://user-images.githubusercontent.com/220427/37579254-e1bd3fd0-2b45-11e8-9462-c69bf320dc55.png)

![image](https://user-images.githubusercontent.com/220427/37579264-ee4f3096-2b45-11e8-9603-96e507bd5697.png)

![image](https://user-images.githubusercontent.com/220427/37579269-f75550ee-2b45-11e8-863d-857ff3beecf0.png)

**Comment by klazuka** [comment]
@mickeyvip the lambda expression parameter alias reference is now fixed. This was just an oversight on my part.

But I wasn't able to reproduce the unresolved reference for the `Random.Extra` package. It worked fine when I tried aliasing it. Does it only screw up if you alias it as `Random`?  Can you try aliasing it to something else like `R`? I'm going to mark this closed, but feel free to create a new issue to provide more details about the module alias problem.

**Comment by mickeyvip** [comment]
@klazuka yes, when I give a name other than `Random` is does not show an error.

**Comment by mickeyvip** [comment]
@klazuka I have `0.9.1` and there are no updates. So how do I get the fix?

**Comment by klazuka** [comment]
@mickeyvip the fix for the lambda expression parameter alias is included in 1.0.0 which I just released this morning.

I still need to fix the bug related to aliased module imports that use the same name.

**Comment by mickeyvip** [comment]
Cool! Thanks!
