### ISSUE TITLE
Lookup by module and name should filter by ElmProject visibility

### ISSUE THREAD

**Issue by klazuka** [klazuka/intellij-elm#212]
We recently started using `ElmNamedElementIndex` to [lookup types by name and module](https://github.com/klazuka/intellij-elm/blob/510a3e08f36ef32da388a056342e447798b1588d/src/main/kotlin/org/elm/ide/inspections/MissingCaseBranchAdder.kt#L82). It's conceivable that someone could have, within the same IntelliJ project, 2 Elm modules with the same name and which also define a type with the same name (i.e. two different versions of the same package).

The reference resolve system handles this for imports by [filtering the results from ElmModuleIndex according to current ElmProject](https://github.com/klazuka/intellij-elm/blob/510a3e08f36ef32da388a056342e447798b1588d/src/main/kotlin/org/elm/lang/core/stubs/index/ElmModulesIndex.kt#L127). We should do something similar here. This is low priority, though, because it should be quite rare.

**Comment by ajalt** [comment]
`ElmNamedElementIndex.findElement` already takes the project to search in, and uses `StubIndex.getElements` to search for elements in files in the given project. Is there more filtering that needs to be done?

**Comment by klazuka** [comment]
The AddImportIntention [also uses the named element index](https://github.com/klazuka/intellij-elm/blob/96409b9449981778bef441061d984e951f79ef01/src/main/kotlin/org/elm/ide/intentions/AddImportIntention.kt#L44), so it probably needs to be fixed, too.
