### ISSUE TITLE
Excessive memory consumption after upgrade to 2.1.1/2.2.0

### ISSUE THREAD

**Issue by martenbr** [klazuka/intellij-elm#213]
After opening out rather large elm project in version 2.1.1 & 2.2.0 and working for a while the memory consumption grows rather quickly. 

I can reproduce it by simply opening the project and opening a few elm files and invoking quick doc on some functions in the file.

I did a heap dump (unfortunately i can't share it) and found that various elm elm typing classes are consuming the memory.
![memory](https://user-images.githubusercontent.com/10561777/51028293-5b70b680-1593-11e9-8ff9-f46d41e4f7a2.png)

I had a quick inside the dump and the issue seems to be cause by a lack of reuse of the typing information (for example i could multiple different TyUnion instances which all represent the rather large Msg type union in one of our elm apps, each of them consuming ~59MB of heap).

**Comment by martenbr** [comment]
Running under PyCharm (tested on both 183.4886.43 and recently released 183.5153.39)

**Comment by martenbr** [comment]
Edit: Also seems to affect 2.1.1, but not 2.1.0

**Comment by klazuka** [comment]
@martenbr how big is your codebase? How many dependencies? Do you have multiple Elm projects in the same IntelliJ project?

**Comment by klazuka** [comment]
@martenbr I just released [version 2.2.1](https://github.com/klazuka/intellij-elm/releases/tag/v2.2.1) which should reduce the memory usage of union types. If you're willing to give it a shot, you can download the plugin zip file from that link. Otherwise, the update will be released in a couple of days by JetBrains via the normal distribution channel.

**Comment by martenbr** [comment]
@klazuka The codebase is 20k lines of elm with 35k lines of library elm, everything is a single elm project. I tested 2.2.1 and memory consumption was significantly lower, comparable to the levels I see when running under 2.1.0.

Thanks & Great work!
