### ISSUE TITLE
False positive for non-exhaustive case expression

### ISSUE THREAD

**Issue by julianpistorius** [klazuka/intellij-elm#214]
It seems PR #211 introduced a bug where it determines a case expression is non-exhaustive when it is actually exhaustive.

I built and tested both the commit that merged the PR (510a3e08f36ef32da388a056342e447798b1588d) and the one before (5cc0a46d20e90dc3e9393b7322672d97318b0232)

I made a simple Elm file with a `case` with a `Bool`:

```elm
module CaseTest exposing (..)

simpleCase : Bool -> String
simpleCase aBoolThing =
    case aBoolThing of
        True ->
            "I think it's True"

        False ->
            "I think it's False"
```

Screenshot with plugin built from 510a3e08f36ef32da388a056342e447798b1588d showing false positive:

![screenshot_510a3e0](https://user-images.githubusercontent.com/742633/51066139-74638100-1600-11e9-9bc6-403531e5b38e.png)

Screenshots with plugin built from 5cc0a46d20e90dc3e9393b7322672d97318b0232 not showing the false positive, as well as showing a true positive:

![screenshot_5cc0a46_02](https://user-images.githubusercontent.com/742633/51066160-8e04c880-1600-11e9-937c-acb1cd70dc28.png)

![screenshot_5cc0a46_01](https://user-images.githubusercontent.com/742633/51066166-93faa980-1600-11e9-8908-1b928c840f8f.png)

**Comment by julianpistorius** [comment]
Note: This was with an Elm 0.19 code base, if that matters.

**Comment by klazuka** [comment]
cc @ajalt

**Comment by rompetomp** [comment]
I still have this issue. When I click alt+enter, and click "Add missing case branches", it adds this:
```elm
        NewUrl string ->
            

        UrlChange unknown ->
```
But these are not in my type definition. I noticed that these Custom Types are actually defined in `~/.elm/0.19.0/package/elm/url/1.0.0/examples/Example.elm`.

**Comment by viktor-ferenczi** [comment]
Same problem happened to the following source code to **update** and **updateLoading**:

```elm
module Page exposing (Msg, State, init, activate, key, subscriptions, update, view)

import Html exposing (Html)
import Http


key : String
key =
    "component"


-- State model

type State
    = Loading
    | Active Model
    | Failed String


type alias Model =
    { x : Int
    }


-- Initial state


init : State
init =
    Loading


-- Activation

activate : Cmd Msg
activate =
    Cmd.none


-- Messages

type Msg
    = Get (Result Http.Error Int)


-- Subscriptions

subscriptions : State -> Sub Msg
subscriptions state =
    Sub.none


-- Update


update : Msg -> State -> ( State, Cmd Msg )
update msg state =
    case state of
		Loading ->
		    updateLoading msg

        Active model ->
		    updateActive msg model

        Failed error ->
            (state, Cmd.none)


updateLoading : Msg -> ( State, Cmd Msg )
updateLoading msg =
	case msg of
		Get result ->
		    case result of
		        Ok x ->
                    ( Active <| Model x
                    , Cmd.none
                    )

                Err reason ->
                    ( Failed reason
                    , Cmd.none
                    )


updateActive : Msg -> Model ->  ( State, Cmd Msg )
updateActive msg model =
    ( Active model
    , Cmd.none
    )


-- View


view : State -> Html Msg
view state =
    case state of
        Loading  ->
            loadingView

        Active model ->
            loadedView model

        Failed reason ->
            Html.div [] [Html.text <|  "Failed: " ++ reason]


loadingView : Html Msg
loadingView =
    Html.div
        []
        [ Html.text  <| "Loading... " ]


loadedView : Model -> Html Msg
loadedView model =
    Html.div
        []
        [ Html.text  <| "x = " ++ String.fromInt model.x ]
```

**Comment by viktor-ferenczi** [comment]
Figured what's triggering the issue: 

This is due to mixing tabs and spaces in indentation, which is invisible. Tabs are not allowed by Elm and it confuses the IDE plugin as well.

Error got from Elm:
```
I ran into a tab, but tabs are not allowed in Elm files.

76| 		    updateLoading msg user

    ^
Replace the tab with spaces.
```

Converting all tabs to spaces using the IDE fixed all issues.

**Comment by klazuka** [comment]
Thanks. I just made #390 to track this.
