### ISSUE TITLE
Ctrl + J doesn't display documentation

### ISSUE THREAD

**Issue by MartinSStewart** [klazuka/intellij-elm#218]
[The feature list page](https://klazuka.github.io/intellij-elm/) mentions that pressing Ctrl + J when a function is selected will display documentation for it.  

When I try to do this however a combo box appears instead.
![image](https://user-images.githubusercontent.com/5068391/51078699-0e3b3480-16ba-11e9-81d1-8f8689c48e46.png)

**Comment by klazuka** [comment]
Pressing `F1` should also work.

Can you try checking your Keymap in IntelliJ's settings? Maybe it's overridden?

**Comment by MartinSStewart** [comment]
`F1` opens IntelliJ documentation in my browser.  Where do I find the keymap setting for showing Elm documentation?  These are the only actions listed: 
![image](https://user-images.githubusercontent.com/5068391/51083341-e0d1a380-1718-11e9-86ac-29a2b56319d1.png)

**Comment by muelli** [comment]
Yeah, the Web page seems to be geared towards Windows and Mac rather GNU/Linux.

I have "Find Action <Ctrl+Shift+A>" in my Help menu. That helped me to find the shortcuts. For the Quick Doc case, it's (the rather unintuitive) `Ctrl+Q`

**Comment by MartinSStewart** [comment]
Ah, there we go. @muelli is right, it's Ctrl+Q (or Alt+MouseWheelClick) for me.  I'm using the default key mapping for IntelliJ, maybe the feature list should mention it can potentially be Ctrl+Q on Windows?

**Comment by klazuka** [comment]
Fixed in 727b93c9353e3738e4c43199bd0692419efe6f66
