### ISSUE TITLE
Elm 18: Unused Import inspection removes Native modules from imports

### ISSUE THREAD

**Issue by Birowsky** [klazuka/intellij-elm#221]
Even tho it's used in module:

<img width="1440" alt="screen shot 2019-01-13 at 01 33 57" src="https://user-images.githubusercontent.com/3199950/51079994-97ab3080-16d3-11e9-85f1-c734b7b0cce7.png">

**Comment by klazuka** [comment]
Just to make sure: is this `Native.Dom` module a Javascript/Elm module?

**Comment by klazuka** [comment]
No problem. I figured as much but just wanted to be sure.
