### ISSUE TITLE
IDEA unable to start up with intellij-elm installed

### ISSUE THREAD

**Issue by KasMA1990** [klazuka/intellij-elm#228]
**Situation**
I start up IDEA as I have done before, also with intellij-elm installed, but now I only get to the "Show Tips" (or hints or whatever it's called) dialog before IDEA freezes. Deleting the intellij-elm plugin from `c:\Users\kma\.IntelliJIdea2018.3\config\plugins\` solved the issue.

**Software**
OS: Windows 10 Enterprise, version 1709
IDEA: 2018.3.3 Ultimate
JRE: 1.8.0_152 (the one bundled with IDEA)
intellij-elm: 2.2.1

**Log**
This is the log produced by IDEA when trying to start, which ends with an intellij-elm message before freezing.
[log-snip.txt](https://github.com/klazuka/intellij-elm/files/2782890/log-snip.txt)

**Side notes**
I had a branch checked out in Git with no Elm code in it, though it has worked before in a similar scenario.

**Comment by klazuka** [comment]
I don't see any errors in the log. But I also don't see it finishing the load of the project dependencies. So perhaps there is an infinite loop in my code when resolving the dependency chain.

Can you add `#org.elm.workspace` to your IntelliJ Debug Log Settings:
<img width="365" alt="screen shot 2019-01-22 at 1 16 34 pm" src="https://user-images.githubusercontent.com/84525/51565919-1a588c00-1e48-11e9-8c3a-eaea11cbdfdb.png">
Then re-enable the Elm plugin and try re-opening IntelliJ. Then send me the log.

Also, if possible, can you send me your `elm.json` file (either here or via email)? Thanks!

**Comment by KasMA1990** [comment]
This is my `elm.json`, though the git branch I was on when opening IDEA did not have anything Elm-related in it.

    {
        "type": "application",
        "source-directories": [
            "src"
        ],
        "elm-version": "0.19.0",
        "dependencies": {
            "direct": {
                "alex-tan/elm-dialog": "1.0.0",
                "elm/browser": "1.0.1",
                "elm/core": "1.0.2",
                "elm/html": "1.0.0"
            },
            "indirect": {
                "elm/json": "1.1.2",
                "elm/time": "1.0.0",
                "elm/url": "1.0.0",
                "elm/virtual-dom": "1.0.2",
                "etaque/elm-response": "3.1.0"
            }
        },
        "test-dependencies": {
            "direct": {},
            "indirect": {}
        }
    }

I'll try to look into the logging.

**Comment by KasMA1990** [comment]
It happened again, though despite having set up the debug logging as you described, the log doesn't have any DEBUG statements in it.
[log-snip2.txt](https://github.com/klazuka/intellij-elm/files/2795118/log-snip2.txt)

One thing that has been in common so far is that this freeze has occurred when I run IDEA after signing out or restarting my machine. Maybe there's something unexpected on the very first run of IDEA?

**Comment by ajalt** [comment]
I run in Windows 10 as well, and I see this same freeze occasionally.  You mentioned that deleting the intellij-elm plugin fixes the freeze, but I find that deleting _any_ plugin also fixes the problem. Given that, and the fact that intellij-elm doen't appear in the logs, I'm not sure that this plugin is at fault.

**Comment by KasMA1990** [comment]
@ajalt weird. I've been using IDEA for a few years without a problem like this, and it only appears after installing intellij-elm. And now I've run for two weeks without the plugin, and everything works fine again 🤷‍♂️

**Comment by klazuka** [comment]
Ok, let’s close it for now. Please reopen if you find that it’s *only* deleting the Elm plugin that fixes the freeze.
