### ISSUE TITLE
Missing case-branch false positive for `Msg` due to named element index not filtering correctly

### ISSUE THREAD

**Issue by perty** [klazuka/intellij-elm#229]
I get this error message despite that the case expression compiles.

"Case expression is not exhaustive less... (⌘F1) 
Inspection info:Under construction"

```
update : Msg -> Model -> ( Model, Cmd Msg )
update msg model =
    case msg of
        SearchProfiles ->
            ( { model | currentPage = ProfileList }, searchProfiles )

        GotSearchResult result ->
            case result of
                Ok search ->
                    ( { model | searchResult = Just search }, Cmd.none )

                Err error ->
                    ( { model | searchResult = Nothing, searchInfo = httpErrorString error }, Cmd.none )
```

**Comment by klazuka** [comment]
@perty the "Under construction" thing is not important in this case: it just means that we haven't provided any documentation for this inspection (the one that checks for `case` branch exhaustiveness).

The real bug here is that you're getting a false-positive error. In your example, which `case` is being marked with the error. Can you show the type definitions that are involved? Or isolate it into a smaller example that reproduces the bug?

Also, please verify that you are running version 2.2.1 of intellij-elm. Thanks.

**Comment by perty** [comment]
Yes, I am using 2.2.1. A big thank you for your hard work. You are making my life as an elm coder a lot easier.

I tried to reduce the code until the warning disappeared but it seems to be state-based. When the code was minimal, I copied it to another project but did not get that warning. So I have two identical projects where the warning is in one of them but not the other. See screenshot.

<img width="1276" alt="screenshot 2019-01-24 at 12 40 04" src="https://user-images.githubusercontent.com/309816/51675880-48b7a200-1fd5-11e9-9413-6b62154b093a.png">

**Comment by perty** [comment]
I have now also tried clearing caches and restart IntelliJ but it has no effect.

**Comment by klazuka** [comment]
Weird. It certainly sounds like a caching bug.

So even after clearing IntelliJ’s cache the flaw-positive error shows up in one project but not the other? What happens if you start typing in a new function definition in the project on the left? Does the error go away?

**Comment by perty** [comment]
No it does not. I get the feeling that once the error is there, it stays.

<img width="340" alt="screenshot 2019-01-24 at 18 21 48" src="https://user-images.githubusercontent.com/309816/51696084-f42c1b00-2004-11e9-9f81-b0372f740284.png">

**Comment by perty** [comment]
I tried removing the project and recreate it. It didn't help. I managed to contaminate the project on the right and now it has also the same problem. Removed the .idea. Removed elm-stuff. Nothing helps.

<img width="285" alt="screenshot 2019-01-24 at 18 46 44" src="https://user-images.githubusercontent.com/309816/51697579-6c481000-2008-11e9-8f69-39c1aeb08481.png">

**Comment by klazuka** [comment]
@ajalt any ideas on what might be going wrong here?

**Comment by klazuka** [comment]
Ok, AJ figured it out. There's a bug in the name resolution / lookup code which particularly affects things like `Msg` where there are many types with the same name. I will fix this in the next release. Thanks for your patience.

**Comment by klazuka** [comment]
@perty as a workaround, try adding a module declaration to the top of your `.elm` file.

**Comment by perty** [comment]
Great that you figured it out but I am afraid the module declaration was not helping. However, renaming the type from Msg to Message, did the trick.

Again, thanks for your hard work. Spending a few hours helping you was the least I could do.
