### ISSUE TITLE
Generated module name is incorrect when file is created with extension

### ISSUE THREAD

**Issue by ajalt** [klazuka/intellij-elm#231]
1. Open the "New elm file" dialog (from the file menu or right licking the project tree)
2. Enter `Foo.elm`, click ok

The file `Foo.elm` is created correctly, but the module declaration in the new file is `module Foo.elm exposing (..)` rather than `module Foo exposing (..)`

![capture](https://user-images.githubusercontent.com/1109214/51644260-71cc2a00-1f24-11e9-9da5-8e82705e8e9f.PNG)
![capture2](https://user-images.githubusercontent.com/1109214/51644262-72fd5700-1f24-11e9-9aec-de6e7d380f56.PNG)

**Comment by klazuka** [comment]
Yeah, that’s lame. I will fix before cutting the next release. There was another bug related to new module creation that I want to fix at the same time.
