### ISSUE TITLE
Examples where record field access completion not working due to parse errors

### ISSUE THREAD

**Issue by klazuka** [klazuka/intellij-elm#238]
It's a known limitation of our type inference implementation that syntax errors will cause type inference to return `TyUnknown`. This was done to make it easier to ship type inference quickly. But eventually we will want to restrict this limitation (or remove it completely).

One way to start would be to just special-case common situations where this limitation is currently affecting the developer experience when writing Elm code. This issue collects real-world examples.

**Comment by klazuka** [comment]
## Beginning a `case` expression

In this example, we want to complete the `statusCode` field on `r`, but it can't because the `case` expression has syntax errors.

```elm
type alias MyRecord = { statusCode : Int }

f : MyRecord -> String
f r =
    case r.
```

**Comment by ajalt** [comment]
## In an expression with an unresolved reference

```elm
type alias MyRecord = { statusCode : Int }

f : MyRecord -> Int
f r =
    foo r.
```

**Comment by ajalt** [comment]
### When passing too many argument to a function

```elm
type alias MyRecord = { field : Int }

f : MyRecord -> Int
f r = 1

g : MyRecord -> Int
g r = f 1 r.
```

This is actually not due to a syntax error, but we currently bail out if we see too many arguments without inferring the argument expressions. This was valid before we returned sub expressions in inference results, but now we should always infer the arguments.
