### ISSUE TITLE
Cannot attach elm.json file.

### ISSUE THREAD

**Issue by chakrit** [klazuka/intellij-elm#241]
![image](https://user-images.githubusercontent.com/45545/51986797-9a7b9300-24d3-11e9-9a77-f45762970062.png)

I'm using 2.2.2 and I guess the cause maybe because I'm using Elm inside a content root inside a GoLand project (not top-level project, also not in intellij or webstorm)

Anyway I can check? I'm using latest of everything at the time of this issue. (elm/intellij/goland/elm-plugin)

**Comment by chakrit** [comment]
Ah, for some reason my `.elm` has a corrupted `elm.json` file in that location. I blasted the entire `.elm` and start all elm-related installation from scratch and it is working again.

Sorry for this!

**Comment by klazuka** [comment]
No problem. Please feel free to post issues whenever you run into trouble.
