### ISSUE TITLE
IntelliJ Elm fails to recognize type-errors that the Elm compiler finds

### ISSUE THREAD

**Issue by z5h** [klazuka/intellij-elm#251]
IntelliJ Elm fails to recognize type-errors that the Elm compiler finds on the command line.
Does IntelliJ Elm not use the elm compiler for error detection?

Is this a known issue?
I can try for an SSCCE.

**Comment by klazuka** [comment]
@z5h the type checking is implemented within the plugin itself. It does not use the Elm compiler at all. That being said, the type system is not fully implemented, although it's getting close now.

So right now you should expect that there are false negatives (code _without_ a red squiggle error in IntelliJ but the Elm compiler says that it is an error). If you have an example at-hand, then go ahead and post it, but I wouldn't go out of your way to.

What you *shouldn't see* are false positives (code _with_ a red squiggle error in IntelliJ but which the Elm compiler is totally fine with). If you run into any of those, please post an example. It doesn't need to be an SSCCE: @ajalt can figure it out, all he needs is an example 😄

**Comment by z5h** [comment]
Ok, this clears up my understanding of the situation. 
If I discover small contained examples, I'll share them.
Thanks.
