### ISSUE TITLE
Plugin fails to identify global elm binary installed in nvm-versioned Node

### ISSUE THREAD

**Issue by jsmesami** [klazuka/intellij-elm#252]
The plugin previously worked well with system-wide node/npm, which in my case symlinked the binaries to ~/.local/bin.

When I had to switch to _nvm_, it fails to recognize _elm_ version when I point it to any of 
~/.nvm/versions/node/v10.15.1/bin (_npm_)
~/.nvm/versions/node/v10.15.1/lib/node_modules/elm/bin (_npm_) 
~/.config/yarn/global/node_modules/elm/bin (_yarn_)
~/.config/yarn/global/node_modules/.bin (_yarn_)
~/.yarn/bin (_yarn_)

Note 
I always use absolute path, _not_ ~/ prefixed path 
_elm_ command is accessible from my system PATH, and works normally. 

![elm](https://user-images.githubusercontent.com/1177566/52368760-7f6acf00-2a4f-11e9-860e-2535e50f7a60.png)

**Comment by klazuka** [comment]
Hmm. So where is the Elm binary actually installed in your nvm environment? I know pretty much nothing about nvm, so I might not be able to help much.

Can you paste in here what happens when you run `elm --version` from your command line? (specifically, invoke `elm` using the exact path that you are providing to the IntelliJ plugin).

**Comment by jsmesami** [comment]
![elm](https://user-images.githubusercontent.com/1177566/52397446-e8852d80-2ab5-11e9-8641-15bc8af29bce.png)
I have investigated further and found out that those elm executables (or symlinks) are in fact node scripts that execute .config/yarn/global/node_modules/elm/bin/elm, which is never executed directly.

Pointing the plugin to _that_ directory works! :tada: 

I wonder if future versions of the plugin could be compatible with this setup, or at least mention this little annoyance in the docs? To prevent some head-scratching for those having similar problem.

Anyways, thank you for the great work!

**Comment by klazuka** [comment]
Thanks for digging into this. I definitely want to make this easy, either by suggesting that path or by figuring out why the node indirection scripts don’t work.

**Comment by yonigibbs** [comment]
In case it's of use to others, the paths below were what I had to use to get this working on Linux, with nvm 0.34.0 and node 10.16.0. I didn't have any problems initially using the symlinked path to the elm binary (`.nvm/versions/node/v10.16.0/bin/`), however for elm-format the symlinked path didn't work so I had to find the binary that the node scripts pointed at:

- elm location: `.nvm/versions/node/v10.16.0/lib/node_modules/elm/bin/elm`
- elm-format location: `.nvm/versions/node/v10.16.0/lib/node_modules/elm-format/unpacked_bin/elm-format`

I was able to directly use `.nvm` without having to explicitly prefix it with `/home/myusername/`.  YMMV.
