### ISSUE TITLE
Problems Panel

### ISSUE THREAD

**Issue by tigp** [klazuka/intellij-elm#286]
First of all, thank you for this awesome plugin. Can't image to live without it!

One question, is it possible to somehow see problems inside problems panel? https://www.jetbrains.com/help/idea/problems-tool-window.html

Thank you!

**Comment by klazuka** [comment]
I was unaware of this feature. I just looked into it briefly and it appears that it's only available as part of their built-in compiler/build system (Java and Kotlin, and maybe some other JVM-based languages).

I did find this ticket in their bug tracker which tracks the feature request for a better Problems view: https://youtrack.jetbrains.com/issue/IDEA-68854.

So I don't think there's anything we can do here. The temporary workaround is to type `Shift-Shift` to bring up search everywhere, then type "run inspection by name" then choose "Type checker" (with the Elm icon). This will inspect your entire project for any type mismatches. I'm not sure if there's a way to do something similar for parse errors.

**Comment by tigp** [comment]
Got it! Thank you for your reply!

I just made a little tool that could be run with JetBrains run configuration, it shows errors with colors that could be clicked and also allows to clear JetBrains console using Grep Console plugin. Maybe it would be useful for you or someone else. https://github.com/tigp/elm-short-clickable-errors

**Comment by klazuka** [comment]
Nice! You may be interested in this issue: https://github.com/klazuka/intellij-elm/issues/83

**Comment by tigp** [comment]
Thank you for pointing to this issue!
