### ISSUE TITLE
False type error when passing a Record or Tuple with multiple Nothings through a pipe

### ISSUE THREAD

**Issue by Herteby** [klazuka/intellij-elm#296]
Talked with @klazuka about this on Slack earlier, I've now found a minimal reproduction:
```Elm
type alias Example =
    ( Maybe String, Maybe Int )


test : Example
test =
    ( Nothing, Nothing )
        |> pipeTest


pipeTest : Example -> Example
pipeTest model =
    model
```
Error:
```
Type mismatch. Required: (Maybe String, Maybe String) → Example Found: Example → Example
```
So it seems like it's confusing the Maybes with each other.

* If you make either value `Just`, then the error disappears.
* If you don't use `|>` or replace it with `<|`, then the error disappears.
* If you add a type definition like this, then the error disappears:
```Elm
test : Example
test =
    let
        example : Example
        example =
            ( Nothing, Nothing )
    in
    example |> pipeTest
```

I think this bug is new to 2.2.4

**Comment by ajalt** [comment]
@Herteby thanks for the excellent reproduction and example!
