### ISSUE TITLE
False positive in type checker on record of dicts

### ISSUE THREAD

**Issue by klazuka** [klazuka/intellij-elm#306]
I found a false positive in [w0rm/elm-mogee Components.elm](https://github.com/w0rm/elm-mogee/blob/966d15c96b8178b7259e7b37b17fe31ef808d051/src/Components/Components.elm#L111), and I was able to reduce it down to the following:

```elm
import Dict exposing (Dict)

type alias MyRecord =
    { chars : Dict Int Char
    , strings : Dict Int String
    }

f : MyRecord
f =
    { chars = Dict.empty
    , strings = Dict.empty
    }
        |> nop

nop : MyRecord -> MyRecord
nop components =
    components
```

The type checker reports an error on `nop`. It gets confused and thinks that *both* the `chars` and `strings` field are of the same type (`Dict Int Char`).

I think the problem is with `|>` because if you instead do normal function application on `nop`, there is no error.

**Comment by klazuka** [comment]
It also appears to be something to do with `Dict`, because if I change the example to use `List Char` and `List String` respectively, the bug goes away.

**Comment by ajalt** [comment]
When building with `master`, I don't see any type errors in that project or in your reproduction. Is your code up to date?

**Comment by klazuka** [comment]
You're right! I was running the elm-test runner branch, which was from 4 days ago and therefore did not include 273bcb6 (freshen the TyVars received from cached inference).

Sorry!
