### ISSUE TITLE
Negated function arguments not parsed properly

### ISSUE THREAD

**Issue by ianmackenzie** [klazuka/intellij-elm#326]
I'm getting a spurious type error on
```elm
Quantity.aXbY dx x -dy y
```
which the Elm compiler parses fine as the `Quantity.aXbY` function taking four arguments `dx`, `x`, `-dy` and `y` but which the `intellij-elm` plugin seems to be parsing as three arguments `dx`, `x - dy` and `y`.

**Comment by klazuka** [comment]
@ianmackenzie I will almost certainly be publishing a bugfix release within the next week. This will be part of it. Thanks for reporting the bug!

**Comment by ianmackenzie** [comment]
Thanks, very quick work!
