### ISSUE TITLE
Wrong error messages inside let/in block

### ISSUE THREAD

**Issue by mickeyvip** [klazuka/intellij-elm#346]
When inside `let`/`in` block and declaring types, often I see an error even the code is valid.

![image](https://user-images.githubusercontent.com/220427/54016850-e4b7fa00-418c-11e9-8a16-57e076c6dfba.png)

![image](https://user-images.githubusercontent.com/220427/54016890-0dd88a80-418d-11e9-95a4-b827a1b34de0.png)

In both screenshots there is an error shown, while the code compiles without errors.

Probably the way to reproduce it it to add a declaration to `let`/`in` block and then add a type annotation to it.

**Comment by ajalt** [comment]
I can reproduce this; it appears to be a cache invalidation issue of some sort.
