### ISSUE TITLE
elm-format & elm must exist in same directory

### ISSUE THREAD

**Issue by ewingrj** [klazuka/intellij-elm#358]
I have elm-format installed via npm & elm installed via the macOS installer. This results in `elm` living in `/usr/local/bin` & `elm-format` living in `~/.nvm/versions/node/v8.11.3/bin/`.

It would be great if I could specify the path for each binary individually.

**Comment by klazuka** [comment]
You should be able to do this. Go to IntelliJ Settings -> Languages & Frameworks -> Elm. You can then specify the path to each tool separately.

**Comment by ewingrj** [comment]
I only see the following:

<img width="778" alt="Screen Shot 2019-03-14 at 3 23 56 PM" src="https://user-images.githubusercontent.com/30963004/54395527-4258b480-466d-11e9-83af-bea8101f60d8.png">

**Comment by klazuka** [comment]
Are you running version 3.0.0 of the plugin? It looks like you have the previous version.

**Comment by ewingrj** [comment]
no I wasn't. I just installed the plugin today, not sure why 2.x was installed.

updating fixed the problem. sorry for the spam issues ;)

**Comment by klazuka** [comment]
No problem. I'd rather that people ask for help then just give up in frustration. Keep posting issues (or contact me on Slack) if you need anything.
