### ISSUE TITLE
Compiler error window doesn't have scrolls

### ISSUE THREAD

**Issue by SergKam** [klazuka/intellij-elm#366]
Thank you for the awesome feature! I just notice a small usability problem.
The Compiler error window doesn't have scrolls so in my setup part of an error message is always out of the screen and cannot be scrolled to view.
![Screenshot at 2019-03-20 13-16-03](https://user-images.githubusercontent.com/3240529/54683677-8850c500-4b12-11e9-932f-d4f95b392f12.png)

**Comment by clojj** [comment]
If you really can't make this toolwindow taller (?) then yes, a vertical scrollbar is missing.

**Comment by klazuka** [comment]
We do support increasing the height of the entire error window, but I think what @SergKam wants is to also be able to scroll within the 2 content panes themself. That way you don't have to constantly be adjusting it.

**Comment by SergKam** [comment]
Of course i can make it bigger but 
- this error window taking too much workspace already and it usually empty.
- some Elm errors are very very very long (in case of "case .. of" :) for example)

**Comment by klazuka** [comment]
I understand. I was just making sure that we were talking about the same thing. We will make it scrollable.

**Comment by klazuka** [comment]
Fixed by #374
