### ISSUE TITLE
elm-format works incorrectly in particular case

### ISSUE THREAD

**Issue by catz** [klazuka/intellij-elm#372]
Hello Keith,

Thanks for the great plugin!
I have found some strange case with elm-format in idea

I can't elm format this code
```
module Test exposing (Some)


type alias Some =
{ 
a : String
}
```
But for example this one formats good. Tried above example from the command line and in atom, everything works.

```
module Test exposing (Some)


type alias Some={a:String}
```

**Comment by catz** [comment]
looks like the duplicate of #341

**Comment by klazuka** [comment]
It will be fixed in the next release (probably in about 2 weeks as I am about to go on vacation).
