### ISSUE TITLE
Explicit imports should shadow wildcard imports

### ISSUE THREAD

**Issue by rosensama** [klazuka/intellij-elm#375]
Just started working with Json.Decode.Pipeline and the plugin cannot parse a pipelined decoder.

The error is: 
> The function expects 1 argument, but it got 2 instead.  
> Inspection info:  The Elm type checker.

```elm
playerDecoder : JD.Decoder Player
playerDecoder =
    JD.succeed Player
        |> required "id" JD.int
        |> required "name" JD.string
```
Love the plug-in.  Thanks so much!

**Comment by ajalt** [comment]
Thanks for the report. What version of the plugin are you using? What version of Elm? Are you able to reproduce this as a complete example that you could share?

**Comment by rosensama** [comment]
Elm:  0.19
Plugin:  3.1.0

I'm using `import Json.Decode.Pipeline exposing (required)` and the compiler picks the right one because those decoders work.   But that was a great hint.  `import Html.Attributes exposing (..)` must put a conflicting required in scope.  intellij-elm was reporting my JDP  import statement as unused.  If I switch to `import Json.Decode.Pipeline as JDP` and then replace all the `required` with `JDP.required` the IDE no longer reports an error.

So maybe I'm getting lucky with the compiler picking the right one?  Just the complier supports this intentionally and you need to, here's a repro.

```elm
import Html.Attributes exposing (..)
import Json.Decode as JD
import Json.Decode.Pipeline exposing (required)

type alias Player =
    { id : Int
    , name : String
    }

playerDecoder : JD.Decoder Player
playerDecoder =
    JD.succeed Player
        |> required "id" JD.int
        |> required "name" JD.string
```
