### ISSUE TITLE
Incorrect error for records with "alias" as field

### ISSUE THREAD

**Issue by stephenreddek** [klazuka/intellij-elm#378]
I have a record with "alias" as a field. The elm compiler allows it, but the plugin type checking gives the error `LOWER_CASE_IDENTIFIER expected, got 'alias'`.

Thanks for all of the hard work on this project! It makes the development experience so much better.

**Comment by ajalt** [comment]
Can you post the code that's causing the error? What version of elm are you using?

**Comment by stephenreddek** [comment]
Elm 0.19

This is a minimal example that causes it.
```Haskell
type alias TypeWithAlias =
    { alias : String
    }
```
