### ISSUE TITLE
Show type information while hoovering over symbols

### ISSUE THREAD

**Issue by viktor-ferenczi** [klazuka/intellij-elm#381]
It would be highly useful to **display type information in a tooltip** while **hovering over symbols** in the editor.  It would save valuable brain power and would help us benefit more from type inference.  It would also help fix compilation errors in the non-trivial cases.

Example of how this works in JetBrains Rider while editing F#:
<img width="664" alt="fsharp-type-info-tooltip" src="https://user-images.githubusercontent.com/1848514/55229015-0fd9ba80-521c-11e9-9e72-4932501f9e19.png">
Hovering over **h3**, mouse cursor is not visible on the screenshot above. Code is from [Giraffe's SampleApp](https://github.com/giraffe-fsharp/Giraffe/tree/master/samples/SampleApp/SampleApp).

**Comment by viktor-ferenczi** [comment]
Found in the project `Readme.md`:

> Press ctrl-shift-p to display the inferred type of the expression under the cursor/caret.

It **does not work for me**, apparently.

Checked the keymap of the Elm plugin in the Settings.  This functionality was missing from the list.  I use the Elm plugin in Rider, together with F# on the backend.  My keymap is based on the Visual Studio layout.

It may be better to just show it with a short delay on hovering symbols instead of having to press a key combination.

**Comment by ajalt** [comment]
You can view and set the keymap for this command by searching for `Type Info` in the keymap settings. I'll update the readme with better instructions.

I think it's very uncommon for this functionality to be exposed on hover, so I'd prefer to keep it as-is.

**Comment by klazuka** [comment]
> I think it's very uncommon for this functionality to be exposed on hover, so I'd prefer to keep it as-is.

The Kotlin plugin shows parameter and return type info when you hover over function calls while holding the `Cmd` key (Mac, not sure what it is on Windows). Right now in our plugin when you hold the `Cmd` key and hover you just get some basic information about the Psi element and the name of the file where it is defined. I don't know how to customize this off-hand, but it's probably pretty easy to do.
