### ISSUE TITLE
Frequent mis-match between disk state and memory state

### ISSUE THREAD

**Issue by simonh1000** [klazuka/intellij-elm#382]
2018.4 version
 
I’m getting a lot of messages about there being a different version of the code in memory and on the disk. If i click on the disk version, I lose edits; if i click on the 'memory' option I often end up saving changes made on other git branches. The messages don't come up immediately so I frequently find myself screwing stuff up, especially after changing branch.

I can't pin this down to this plugin because I only intellj one way - to do elm with this plugin

**Comment by ajalt** [comment]
Do you have an external file watcher that runs elm format or similar? People have had similar problems in the past with those. 

elm-format is now integrated into the plugin. You can configure it to run on save in Settings > Languages > Elm.

**Comment by simonh1000** [comment]
I am running webpack in the background, but while it IS compiling (and providing a dev server), it is NOT running elm-format

**Comment by klazuka** [comment]
I'm back from vacation now. I'll see if I can reproduce this.

In the meantime, which OS are you using? Do you have elm-format configured to run automatically in the intellij-elm settings ("run when file saved")? 

We use webpack-dev-server at work, and we don't have this problem, so I doubt that's it.

**Comment by simonh1000** [comment]
I'm on MacOs (Mojave and do have that option clicked). I have a colleague working with the same stack and they are not experiencing the same problems it seems. I will do some digging with them too

**Comment by simonh1000** [comment]
I think it may be due to the synchronisation settings. I turned off save on blur because (especially with 0.18) you don't want to compile too often. I also turned off the sync option at the same time - I will try for a while with that turned back on 
![image](https://user-images.githubusercontent.com/5256724/55381196-c42c5700-5522-11e9-852c-b869f0cce37c.png)
