### ISSUE TITLE
Modifying src directories breaks intellij-elm

### ISSUE THREAD

**Issue by z5h** [klazuka/intellij-elm#385]
In my elm.json `dependencies/direct` I have a package I author.
To test an upgrade to that dependency before I publish it, I added it to elm.json src, and removed it from the dependencies.

intellij-elm no longer registers the modules in that dependency. 
Restarting Webstorm has no effect.

The elm compiler and other editors don't have the problem, so I have good reason to believe my code/elm.json aren't the problem.

**Comment by klazuka** [comment]
can you post your `elm.json` file? (or send it to me on Slack or email)

**Comment by z5h** [comment]
Closing because this report doesn't isolate the actual issue.

I've created a more appropriate issue at #386.
