### ISSUE TITLE
intellij type checker reports error in valid code

### ISSUE THREAD

**Issue by simonh1000** [klazuka/intellij-elm#388]
here's a small repro
```
module Test exposing (MyTest, foo)


type alias MyTest =
    { mod : String }


foo : Maybe MyTest -> Bool
foo m =
    let
        mbM =
            [ m ]
                |> List.head
    in
    case mbM of
        Just { mod } ->
            mod == ""

        Nothing ->
            False
```

**Comment by ajalt** [comment]
This repro is not valid code: https://ellie-app.com/5mfsRFHZymba1

The plugin reports the same error as the Elm compiler.

**Comment by simonh1000** [comment]
hmmm, you're right. let me relook at my attempt to create a SSCCE, as I do have something marked as wrong by intellij but which compiles

**Comment by klazuka** [comment]
Closing for now. Please re-open if you have another example.

**Comment by simonh1000** [comment]
there's a challenge - try https://ellie-app.com/5rZs9njLMY3a1
