### ISSUE TITLE
Get error "Type mismatch" when using type variables

### ISSUE THREAD

**Issue by holgerl** [klazuka/intellij-elm#402]
When using type variables, the elm plugin give a compile error even though it compiles perfectly in `elm make`

![image](https://user-images.githubusercontent.com/617535/57705847-e7d7d680-7664-11e9-8941-717326206d46.png)

I am using v3.1.1 of the intellij-elm plugin.

**Comment by ajalt** [comment]
Thanks for the report. The code in your picture doesn't produce an error for me. Would you be able to post a complete file that reproduces the problem if it were placed in a project by itself?

**Comment by holgerl** [comment]
Yes, I have now found out that it only happens if the code is in a `let ... in` block:

```
module Test exposing (..)

myThing =
    let
        myMaybe =
            Just "Foo"

        myMap : a -> a
        myMap a =
            a

        result =
            Maybe.map myMap myMaybe
    in
        result
```

**Comment by ajalt** [comment]
For reference, here's a failing test case:
```kotlin
    fun `test passing function with vars in annotiation in let to flex vars`() = checkByText("""
foo : (a -> b) -> a -> b
foo f a = f a

main : ()
main =
    let
        b : a -> a
        b a = a
    in
    <error descr="Type mismatch.Required: ()Found: String">foo b ""</error>
""")
