### ISSUE TITLE
Intellij eats all the memory and becomes unresponsive

### ISSUE THREAD

**Issue by smucode** [klazuka/intellij-elm#409]
I'm using intellij community edition and the intellij-elm plugin. I only use it for elm development, so not any other plugins installed (apart from a theme).

A few times a day intellij consumes a lot of memory and cpu. I have now configured it to use 8gb and it eats all of it. At the same time the editor becomes unresponsive for long periods of time. I usually have to restart idea, sometime it doesn't help even.

Usually it seems to trigger when there are compilation errors. I'm running webpack on the side, that compiles when there are changes.

On a macbook pro, latest osx version. We have a fairly large elm project, 75k loc, 350 modules. I only have one project open at a time.

Let me know if there is anything i can do to help debug this. Love the great work you are doing.

**Comment by klazuka** [comment]
My main Elm codebase is 25k LOC and 151 modules. It runs comfortably in <2GB RAM.

We *do* heavily cache data, so I wouldn't be surprised if there's too much caching for projects like yours. Could you run a heap dump and send it to me (either by email, Slack, whatever)?

JetBrains has instructions for capturing a memory snapshot here: https://intellij-support.jetbrains.com/hc/en-us/articles/207241235-Reporting-performance-problems

**Comment by smucode** [comment]
Sorry for the delay, left for vacation. I will share memory snapshot privately.

**Comment by klazuka** [comment]
Looks like the memory is being consumed by the type inference system.

<img width="1353" alt="Screen Shot 2019-06-11 at 9 54 06 AM" src="https://user-images.githubusercontent.com/84525/59291116-f519be00-8c2e-11e9-9df7-dec4a65b5476.png">

**Comment by klazuka** [comment]
I gave @smucode a beta build with the fix last night. He confirmed that it solved the problem. Nice work @ajalt
