### ISSUE TITLE
Elm 0.19 compatibility

### ISSUE THREAD

**Issue by klazuka** [klazuka/intellij-elm#41]
Things that will need to be fixed:

- [x] packages are now installed in ~/.elm (by default). This will probably be the hardest thing to fix because we will now need to get in the business of parsing the `elm.json` file to determine which packages are actually in scope.
- [x] String and Char are no longer built-in types. Need to add them to implicit global scope
- [x] The (!) operator no longer exists in Platform.Cmd. Need to delete it from implicit global scope.
- [ ] union constructors are either _all_ exposed or only a single constructor is exposed (??? this appears to be in flux still)
- [x] the `\x` escape code in String and Char literals has been changed to `\u{0000}` (e.g. `\xff` => `\u{00ff}`)
- [x] tuple constructor functions have been removed (e.g. `(,)` and `(,,)`)
- [x] qualified imports of implicitly imported modules are broken
        - `isCore` check needs to accomodate the new path structure
        - packages becomes singular
        - e.g. `/Users/keith/.elm/0.19.0/package/elm-lang/core/6.0.0/src/List.elm`
- [x] infix operators are defined with new syntax (see elm-lang/core/Basics.elm) and they are not permitted in normal user programs
- [x] Native -> Elm.Kernel

Open Questions:
- which kinds of packages are allowed to define infix operators?
- can an infix operator be used as a function still (e.g. with List.map)? **YES, it can**

**Comment by muelli** [comment]
> packages are now installed in ~/.elm (by default).

do you have a reference? I'm wondering how easy that will be to tweak, because the Gitlab CI only likes to cache files under a certain directory IIRC.

**Comment by klazuka** [comment]
@muelli there is an `ELM_HOME` environment variable which allows you to override this.

**Comment by klazuka** [comment]
Merged to master but won’t release until Elm 0.19 is released.
