### ISSUE TITLE
New project template isn't showing up in WebStorm

### ISSUE THREAD

**Issue by klazuka** [klazuka/intellij-elm#414]
A user reported that "Elm" doesn't show up in WebStorm when creating a new project. I confirmed that it is definitely broken in WebStorm 2018.3 (and probably other versions).

<img width="862" alt="Screen Shot 2019-06-03 at 3 02 44 PM" src="https://user-images.githubusercontent.com/84525/58837522-a8235f80-8610-11e9-8ecd-842df59ef79d.png">

**Comment by nurbek-ab** [comment]
I can confirm this. No Elm template in WebStorm 2019.1.3

**Comment by willismonroe** [comment]
Still does not appear in 2020.2.1
