### ISSUE TITLE
Ctrl-J displays the wrong type information or none at all

### ISSUE THREAD

**Issue by simonolander** [klazuka/intellij-elm#425]
Ctrl-J does not produce the correct type for variables and functions declared in let statements. 

#### Example:
```elm
base arg1 =
     let
         fun1 arg2 =
             arg2 + 1
 
         fun2 arg3 =
             ( arg3, False )
 
         res1 =
             fun1 arg1
 
         ( res2, res3 ) =
             fun2 arg1
     in
     ( res1, res2, res3 )
```
Here, `fun1`, `fun2` and `res1` all show the same type as `base`:
```
fun1 : number → (number, number, Bool)
fun1 arg2 defined in Main
```
The tuple deconstruction `res2` and `res3` get no type at all:
```
No documentation found.
```

The first looks like a bug and the second like a feature request.

**Comment by ajalt** [comment]
Thanks for the report. This was fixed in #416, which will be included in the next release.

**Comment by simonolander** [comment]
Cool. Is there a rough release cycle that you follow?

**Comment by klazuka** [comment]
I used to release roughly every 2 weeks, but I moved across the US last month, and I've been busy. The good news is that I'm about to make a release right now 😄

**Comment by simonolander** [comment]
Nice! It's a great plugin, thanks for your work! :)
