### ISSUE TITLE
Your plugin also seems unusable

### ISSUE THREAD

**Issue by RobertBrown3** [klazuka/intellij-elm#43]
Thanks for the info that you provided for the issue I posted in the durkiewicz Elm plugin page. I especially thank you for your prompt response (I don't get that very often! :-( ).

I have just installed your rewrite using the method you suggested.

Unfortunately, I still have the problems I had with the previous plugin. No Elm project. No known way to create Elm files or otherwise engage the plugin. Worse, no documentation on how to use this plugin. Effectively, I still have a plugin that, aside from showing that it is installed and enabled, appears to not do anything.

So how do I engage this plugin? Are you planning to do any documentation on how to engage and use this plugin?

**Comment by klazuka** [comment]
See https://github.com/durkiewicz/elm-plugin/issues/81#issuecomment-391362921
