### ISSUE TITLE
Unresolved references for Elm 0.18 projects in WebStorm 2019.2

### ISSUE THREAD

**Issue by Birowsky** [klazuka/intellij-elm#442]
- I cloned [this repo](https://github.com/fedragon/elm-project-template) as a sample .18 project
- ran `elm-package install`
- clicked on [Attach elm.json (or elm-package.json)]
- got the error below

<img width="1137" alt="Screen Shot 2019-07-24 at 10 12 18" src="https://user-images.githubusercontent.com/3199950/61777277-f24ce400-adfc-11e9-84d2-c5fa64ed18c7.png">

<img width="456" alt="Screen Shot 2019-07-24 at 10 13 28" src="https://user-images.githubusercontent.com/3199950/61776645-bcf3c680-adfb-11e9-86b7-669d33ad7a42.png">

------

The reason I'm asking this is because in my own private project, since one of the recent versions of the plugin, the installed packages got lost:

<img width="399" alt="image" src="https://user-images.githubusercontent.com/3199950/61777049-8f5b4d00-adfc-11e9-8474-631d33dd1b52.png">

I wasn't really active, so I did not notice when exactly did it happen.

**Comment by klazuka** [comment]
works for me. Are you sure that you ran `elm-package install` in the `template` directory? Because there is another `elm-package.json` file in the root, but if you only install that one, you will get the error that you are seeing.

**Comment by klazuka** [comment]
As for 0.18.0, no, we haven't dropped support for it, but I will soon.

**Comment by Birowsky** [comment]
You were right about me choosing the wrong `elm-package.json`. After picking the correct one, I don't get the error box, however, I still experience the behavior that I mentioned where the installed packages can not be referenced:

<img width="805" alt="Screen Shot 2019-07-24 at 18 37 24" src="https://user-images.githubusercontent.com/3199950/61811611-1848a780-ae42-11e9-9795-2cc7a9e2c223.png">


I even tried with an older version of the plugin, the problem is still there. Do you have any idea of what should I check next?

**Comment by klazuka** [comment]
Maybe IntelliJ's cache got messed up? Try File -> Invalidate Caches & Restart

Also, can you verify that `exact-dependencies.json` looks good and that any packages that it refers to actually exist on disk?

**Comment by Birowsky** [comment]
Got some news. Tried everything on another machine: It had an old WebStorm and an old Elm plugin, and the issue was not there. 

However, since installing the latest WebStorm, the issue is there too:

<img width="499" alt="Screen Shot 2019-07-24 at 20 33 18" src="https://user-images.githubusercontent.com/3199950/61819086-9614af00-ae52-11e9-9442-7f378e25a8ae.png">

So.. have you tried the latest WebStorm? `2019.2`?

**Comment by klazuka** [comment]
Try marking the `elm-stuff` directory as "not excluded". It appears to work differently in WebStorm vs IDEA.

**Comment by Birowsky** [comment]
Yap, that did it!

You da man.

You decide whether you gonna leave this as an issue or not.

**Comment by klazuka** [comment]
Closing this since there is a workaround, and I really can't keep supporting Elm 0.18
