### ISSUE TITLE
Show usages should only list function calls

### ISSUE THREAD

**Issue by MartinSStewart** [klazuka/intellij-elm#469]
![Screen Shot 2019-08-13 at 11 33 39 AM](https://user-images.githubusercontent.com/5068391/62931210-37da4c80-bdbe-11e9-8fba-2e7f4fc21c62.png)

Here I'm checking usages of this function. It looks like there are 2 usages but one is the exposing text and the other is the type annotation*. To me this is distracting information. What I want to see is just where this function is invoked. 

*This function should also be marked as unused but I think that's covered in #336

**Comment by klazuka** [comment]
See #177 for a workaround for type annotation. In general, JetBrains does not give us much control over filtering this list, and we have resorted to hacks by piggy-backing on the import hiding. I guess we could do the same thing with the module’s exposing list.

**Comment by MartinSStewart** [comment]
The work around seems to have some odd behavior.

If I show usages here I get a list of function calls plus exposing text and annotation.
![Screen Shot 2019-08-13 at 1 52 52 PM](https://user-images.githubusercontent.com/5068391/62939566-e471f980-bdd1-11e9-89bb-27a4957601c5.png)

If I toggle `Show imports statements` then the exposing and type annotation are hidden but so are two of the function calls.
![Screen Shot 2019-08-13 at 1 53 01 PM](https://user-images.githubusercontent.com/5068391/62939564-e471f980-bdd1-11e9-93b3-832a8057614b.png)

If I toggle it a second time only one of the incorrectly hidden function calls is shown again.
![Screen Shot 2019-08-13 at 1 53 08 PM](https://user-images.githubusercontent.com/5068391/62939567-e471f980-bdd1-11e9-86ae-3f9de57aceef.png)

**Comment by ajalt** [comment]
This is a problem with the IntelliJ's find usages window in general. If you toggle any of the visibility options in the popup dialog, incorrect results can be shown until you close the popup and re-open it. This happens for other languages as well.
