### ISSUE TITLE
Not resolving local dependencies

### ISSUE THREAD

**Issue by raymanoz** [klazuka/intellij-elm#470]
Since `3.3.0`, the plugin seems to not be able to resolve locally installed dependencies. Local files in the project are resolved OK.

![image](https://user-images.githubusercontent.com/20589/63000952-c4b40180-beb5-11e9-860d-e4493eb8abcb.png)

I'm using elm `0.18`

**Comment by raymanoz** [comment]
The problem was that the gradle import marked the `elm-stuff` directory as "excluded".

Right-click, mark directory as "Not excluded" fixes it.

![image](https://user-images.githubusercontent.com/20589/63017829-a6143180-beda-11e9-8699-a03f5b7a427c.png)

**Comment by klazuka** [comment]
Dupe of #442 . See that issue for more details. If someone wants to debug it, I'd be happy to take a patch.
