### ISSUE TITLE
Import errors don't take you to the error

### ISSUE THREAD

**Issue by francescortiz** [klazuka/intellij-elm#474]
Import errors don't take you to the file when you click on them in the Elm Compiler tool window.

![image](https://user-images.githubusercontent.com/655264/63328067-bccde480-c32f-11e9-854f-366e7ddb250d.png)
It would be good if at least it took you the file with the error, specially on big projects.

Thanks!

**Comment by klazuka** [comment]
The problem is that `elm make --report json` is not including the location:
```
{"type":"error","path":null,"title":"FILE NOT FOUND","message":["You want me to compile this file:\n\n    ",{"bold":false,"underline":false,"color":"yellow","string":"Api.elm"},"\n\nI cannot find it though! Is there a typo?"]}
```

This is a bug (or deficiency) in the Elm compiler.

**Comment by francescortiz** [comment]
It seems to be fixed in the new compiler version. Thank you for your feedback
