### ISSUE TITLE
Record field renaming not works in some specific cases (really deep)

### ISSUE THREAD

**Issue by justgook** [klazuka/intellij-elm#475]
here i rename it:
https://github.com/justgook/platformer/blob/develop/lib/elm-logic-templates/src/Logic/Template/Game/ShootEmUp.elm#L138

here it is not renamed:
https://github.com/justgook/platformer/blob/develop/lib/elm-logic-templates/src/Logic/Template/Game/ShootEmUp.elm#L561

**Comment by klazuka** [comment]
I'll leave it for @ajalt to say whether this is even possible to fix, but a workaround would be to factor out the lambda, `\_ ( entityID, world ) -> ( entityID, { world | camera = entityID } )`, and give it a type annotation. 

Elm's records are structurally typed where the name doesn't matter: only the shape of the fields. But when doing a field rename, we want to do the rename only on the definition that you expect, ignoring any other record definitions that also happen to have the same shape. So the plugin needs to be able to trace it all the way back to the type alias definition. And the type annotation can help us do that.

AJ's algorithm does the best it can to keep track of the types through nested functions, but it's tricky. Adding a type annotation should help.

**Comment by justgook** [comment]
that was what i kind of expected - it already do a lot - and something like that would be just nice - idk maybe You just not have such example (for me what it do already is kind of magic)
