### ISSUE TITLE
Plugin reports unused record fields in case of record destructuring

### ISSUE THREAD

**Issue by szubtsovskiy** [klazuka/intellij-elm#476]
Hey there!

First of all let me express my big gratitude for this plug-in as it is helping enormously and brings my developer experience to great heights. Existence of this plug-in, its rich set of features and overall great reliability often make it easy to do changes in several files without hitting Cmd+S single time and thus not seeing any compiler error which is a personal point of satisfaction. :-)

However, after updating to 3.4.0 I have immediately discovered that it started marking some of my record fields as unused for the sole reason of using these records in a destructured manner only. This brings reliability down significantly as I know I can't rely on usage search anymore and have to resort to full-text search again. 

Please find SSCCE in [Ellie](https://ellie-app.com/6r6rm5ftdRda1) or below. Both fields in `Flags` are marked as unused despite on the type annotations.

**Screenshot:**
![Screenshot 2019-08-20 at 13 04 44](https://user-images.githubusercontent.com/1901687/63338246-1d1e4f80-c34b-11e9-8e87-e9440569fb95.png)

**Source:** (also in [Ellie](https://ellie-app.com/6r6rm5ftdRda1))
```
module Sscce exposing (main)

import Browser exposing (Document)


type alias Flags =
    { flag1 : Int
    , flag2 : String
    }


type alias Model =
    ( Int, String )


init : Flags -> ( Model, Cmd () )
init ({ flag1, flag2 } as flags) =
    let
        _ =
            Debug.log "TEST" ( test1 flags, test2 flags )
    in
    ( ( flag1, flag2 )
    , Cmd.none
    )


test1 : Flags -> String
test1 { flag1 } =
    String.fromInt flag1


test2 : Flags -> String
test2 { flag2 } =
    flag2


main : Program Flags Model ()
main =
    Browser.document
        { init = init
        , update = \() model -> ( model, Cmd.none )
        , view = always (Document "SSCCE" [])
        , subscriptions = always Sub.none
        }
```

**Comment by klazuka** [comment]
This is a bug caused by complications related to destructured parameters, `{flag1, flag2}`. The problem is that in some cases they need to behave as "named elements" (i.e. introduce a name) and in others as "reference elements" (i.e. refer to a name that has already been introduced).

@ajalt looked into this and ran into some problems with the way that Find Usages worked when an element was both a named element and a reference element. AJ, is this the same problem that you were looking into?
