### ISSUE TITLE
intellij type checker reports error in valid code

### ISSUE THREAD

**Issue by Janiczek** [klazuka/intellij-elm#482]
SSCCE:
```elm
module Main exposing (main)


main : Program () (Model Record) ()
main =
    Platform.worker
        { init = init
        , update = \() model -> ( model, Cmd.none )
        , subscriptions = always Sub.none
        }


type Model a
    = CustomType (Model_ a)


type alias Model_ a =
    { a | extraField : () }


type alias Record =
    { field : () }


init : () -> ( Model Record, Cmd () )
init () =
    ( CustomType
        { field = ()
        , extraField = ()
        }
    , Cmd.none
    )
```

Elm 0.19.1: `Success! Compiled 1 module.`
intellij-elm (in the definition of `init`):
```
Type mismatch.
Required: (Model Record, Cmd ())
Found: (Model { field : (), extraField : () }, Cmd ())
```

![err1](https://user-images.githubusercontent.com/149425/63459945-d10c0180-c455-11e9-8c5c-fa49987f40a4.png)
![err2](https://user-images.githubusercontent.com/149425/63459944-d0736b00-c455-11e9-80fc-7c240e3f0e76.png)

**Comment by ajalt** [comment]
Thanks for the SSCCE. Here's a fully minified reproduction:

```elm
type Foo a = Foo (Outer a)
type alias Outer a = { a | f2 : () }
type alias Record = { f1 : () }

main : Foo Record
main = Foo { f1 = () , f2 = () }
```

[Here's an ellie](https://ellie-app.com/6rMRTMpTfk2a1) with an example of where we differ in behavior from the compiler. 

I would absolutely expect that code to work, but apparently using an extension record alias constructor as a parameter of a union variant causes fields to be _removed_ from the argument type when you construct that variant. That's not how record extensions work in any other context.

Although I normally replicate the compiler bugs I find, this one would be enough work that I might not take it on.

**Comment by klazuka** [comment]
@Janiczek If you can get @evancz on the record saying that the Elm compiler's behavior in this case is intentional, we will reconsider fixing this. But for now, I'm just going to close it. Sorry.
