### ISSUE TITLE
Cannot find your Elm app's main entry point. Please make sure that it has a type annotation.

### ISSUE THREAD

**Issue by gurdiga** [klazuka/intellij-elm#483]
Hi! 👋

After upgrading the plugin to 3.4.0, it can’t resolve the non-local references. For example if I import something from one of my files, it’s recognized, but for the external libraries, for example `Browser`, `Html`, `Html.Attributes`, it says `Unresolved reference 'Browser'`. 😑

I see this error message in the Event Log panel:
```
09:20 Cannot find your Elm app's main entry point. Please make sure that it has a type annotation.
```

I have an app with multiple entry-points: one for every page. This means that I don’t have a root `Main.elm`, but instead every page has its own entry-point; for example: [`AuthenticationPage.elm`](https://github.com/gurdiga/repetitor/blob/d1af493f2cc86341efee828a05f3232320a03a64/src/Tutor/Pages/AuthenticationPage.elm), [`RegistrationPage.elm`](https://github.com/gurdiga/repetitor/blob/d1af493f2cc86341efee828a05f3232320a03a64/src/Tutor/Pages/RegistrationPage.elm), etc.

NOTE: Version 3.3.0 of the plugin works well. 🤓

Sorry for not offering an SSCCE, I don’t know how to prepare one for this particular issue. My [project’s source code](https://github.com/gurdiga/repetitor/tree/d1af493f2cc86341efee828a05f3232320a03a64) is publicly available if it helps.

Here is a screenshot:

![screenshot](https://user-images.githubusercontent.com/53922/63491325-92129600-c4bf-11e9-9bbe-17873bd05797.png)

Thank you for the awesomely useful plugin! 🙂

**Comment by klazuka** [comment]
Something went wrong with IntelliJ's caches during the upgrade. Can you try `File -> Invalidate Caches & Restart`?

The error message about not being to find the Elm app's main entry point is unrelated to these unresolved references.

**Comment by gurdiga** [comment]
That solved it! Thank you! 🤩

**Comment by Erudition** [comment]
Just had the same issue after starting IDEA one day. Good thing I found this issue!
Probably should announce the solution somewhere more accessible
