### ISSUE TITLE
ProjectLoadException when setting up elm.json

### ISSUE THREAD

**Issue by Aarkon** [klazuka/intellij-elm#497]
I have a running project on machine A. Then I open it on machine B, files are synced using git. elm-plugin asks me to set up my toolchain and elm.json. The former works, the latter produces the error in the screenshot.

![image](https://user-images.githubusercontent.com/4244486/63999880-ca8c2280-cb04-11e9-80fd-44456e641187.png)

For machine readability: The text is:
`Failed to attach Elm project`
`org.elm.workspace.ProjectLoadException: Could not find file /home/$USER/.elm/0.19.0/package/elm/http/2.0.0/elm.json. Is the package installed?`
(I replaced my username with $USER of course).

This error happened to me on multiple occasions, another one being loading an elm.json that is not in the uppermost directory of the project or when the sources are misplaced respectively. It pops up both on machines A and B, so I presume it is not an issue of a certain installation.
I can not figure out a workaround at this point, which is a great bummer in an otherwise great plugin.

**Comment by klazuka** [comment]
Sorry for the delay—I was travelling. Is your project an application or a package? Can you post your `elm.json` file (or send it to me privately via Slack)?

**Comment by Aarkon** [comment]
Of course! But the issue happens on multiple projects, even on quite a freshly initiated ones. Nothing special in this file.

`elm.json`:
```
{
    "type": "application",
    "source-directories": [
        "src"
    ],
    "elm-version": "0.19.0",
    "dependencies": {
        "direct": {
            "elm/browser": "1.0.1",
            "elm/core": "1.0.2",
            "elm/html": "1.0.0"
        },
        "indirect": {
            "elm/json": "1.1.3",
            "elm/time": "1.0.0",
            "elm/url": "1.0.0",
            "elm/virtual-dom": "1.0.2"
        }
    },
    "test-dependencies": {
        "direct": {},
        "indirect": {}
    }
}
```

**Comment by klazuka** [comment]
I'm surprised that `elm/http` is not even in the indirect dependencies list. Are you sure that this is the file you are having trouble with?

I created a dummy project using your `elm.json` above and a file `src/Main.elm` whose contents are:

```elm
import Html

main = Html.text "hi"
```

It loads fine on my computer (macOS, IntelliJ IDEA Ultimate 2019.2)

**Comment by Aarkon** [comment]
Yes, I am. As I said, I can not recreate this reliably though. It happens from time to time and sometimes not at all. The issue rarely arises when creating a new project though, yet very often when e.g. I check out one from git.

**Comment by izmajlowiczl** [comment]
I've encountered the same issue. What helped was manually removing the json import from elm.json, rebuilding, and reverting back the json dependency.

**Comment by Aarkon** [comment]
I just came along this again and once calling `elm make src/Main.elm` initially appears to be a workaround at least in a fresh project.

**Comment by Namek** [comment]
It's about `elm/browser` instead of `elm/http` in my case:
![image](https://user-images.githubusercontent.com/31058/71558027-dbb35480-2a4e-11ea-82af-ec7790d10107.png)

It works when the `elm-stuff` folder is downloaded.

**Comment by klazuka** [comment]
This plugin assumes that you have already downloaded your dependencies from the command line using Elm's package manager.

I will see what I can do to improve the error message.

**Comment by klazuka** [comment]
Hm. I can't reproduce this error. I do have better error messaging already in place for the common case where you try to load a dependency and it has not yet been locally installed. And that is working fine. But there must be some edge case that is taking this path. Needs further investigation, but I'm on vacation right now.

**Comment by Namek** [comment]
@klazuka Try not having both Elm's global cache and `elm-stuff` in the project's folder. Have a nice vacation.

**Comment by Aarkon** [comment]
Yeah, enjoy your days off! Especially since I have a way to get around the issue like it seems.
