### ISSUE TITLE
Elm Compiler tool shows 0 errors no matter what

### ISSUE THREAD

**Issue by francescortiz** [klazuka/intellij-elm#498]
It is the same issue than #471

It appears to be random. It is present on distinct IDE (webstorm, pycharm), opening the project as part of another bigger project or alone, having many files with main function or just one. Is there anything I can do to debug it?

**Comment by klazuka** [comment]
Are you using Elm 0.19 or 18? Is it an application project or a package? What is the type of your `main` function? Does it have a type annotation?

**Comment by francescortiz** [comment]
Sorry, when I said that it is the same issue than #471 I meant that we are working on the same project.

**Comment by klazuka** [comment]
Clone the `intellij-elm` project. Open the directory in IDEA community or ultimate. Gradle will sync dependencies for a few minutes. 

Set a breakpoint on `org.elm.workspace.compiler.ElmBuildAction#actionPerformed`.

Click the 'Gradle' button on the right-side of the main IDEA window (should be near/next-to the 'Elm' projects button). Go to `Tasks -> intellij`. Right-click `runIde` and choose `Debug`. 

It will spawn a new instance of the IDE: open your Elm project and reproduce the bug. It should break in the debugger and you can step through the code from there.

**Comment by francescortiz** [comment]
Thanks for such clear instructions. Just to keep you updated, I have the setup ready. As soon as we step into I will debug it.
