### ISSUE TITLE
Can't get rid of "Could not determine Elm compiler version"

### ISSUE THREAD

**Issue by samrensenhouse** [klazuka/intellij-elm#503]
Whenever I open up my project I can't get rid of the popup that says Could not determine Elm compiler version. The toolchain appears to be setup correctly, and it shows the version inside the settings.

![image](https://user-images.githubusercontent.com/22641341/64290418-adec5200-cf2b-11e9-8d11-377b91dc43bf.png)

Tried deleting my node modules, invalidating the cache and restarting. Neither of which seemed to do anything.

**Comment by klazuka** [comment]
Maybe it's timing out running npm-wrapped Elm?

Can you try installing Elm with the official installer and see if that works better?

And one last question, are you using the `0.19.0-no-deps` version of the `elm` package on npm?

**Comment by samrensenhouse** [comment]
I am currently using the 0.19.0-bugfix6 of the elm package on npm

**Comment by klazuka** [comment]
Try the no-deps one (which is the newest, and I think simplifies some things, although it may be unrelated).

**Comment by samrensenhouse** [comment]
Updated the package to no-deps, but now I get an error when fetching the version on the settings page:

![image](https://user-images.githubusercontent.com/22641341/64295458-c7df6200-cf36-11e9-87b1-f0bb625a38af.png)

Copying the path leads to it running just fine
```
(insight) λ C:\dev\insight\client\node_modules\.bin\elm.cmd --version
0.19.0
```

I am going to try the windows installer for elm and see how that goes

**Comment by samrensenhouse** [comment]
Using the windows installer fixed the issue for me, thanks!

It seemed to instantly return the version, where before when I use the auto discover it would pause a moment before the version would pop up.

**Comment by klazuka** [comment]
There’s something strange about npm Haskell tools where they launch slow in some cases.
