### ISSUE TITLE
Degraded performance in 3.4.2

### ISSUE THREAD

**Issue by smucode** [klazuka/intellij-elm#510]
After upgrading to 3.4.2 i see substantial performance degradation. In certain large files this was a problem in the past too, but now even smaller files (couple of hundred LOC) take 5-10 seconds before the plugin is able to report errors. 

When it was isolated to certain large files, i was able to live with it. But now, when it's a problem across the board, it just destroys the dx. 

Reverting back to 3.3.0 works the best for me.

**Comment by Abubabubi** [comment]
Sadly I can't share the code. RAM usage seems alright, got 16gb and I don't have restriction for Intellij.
It seems files with errors actually have the performance issues rather than those that don't. So maybe it's just the perception issue.

**Comment by smucode** [comment]
I had idea set up with the default ram settings, bumped it a lot and have been testing 3.4.2 this morning. Haven't had any major performance issues yet, will test some more and get back to you. Seeing more false positive errors than in previous versions, but i think this is being addressed.

**Comment by WhileTruu** [comment]
I get solid perf issues and freezing as well, often for several seconds, when modifying files with a large amount of errors in them.

**Comment by klazuka** [comment]
If possible, please use Intelli-J’s CPU profiler to send me a trace: https://intellij-support.jetbrains.com/hc/en-us/articles/207241235-Reporting-performance-problems

If you suspect that it’s high memory usage, then a memory snapshot would be helpful.

**Comment by WhileTruu** [comment]
[IU-192.6603.28_bleepbloop_13.09.2019_14.52.54.snapshot.zip](https://github.com/klazuka/intellij-elm/files/3609930/IU-192.6603.28_bleepbloop_13.09.2019_14.52.54.snapshot.zip)

**Comment by klazuka** [comment]
Thanks but the file appears to be corrupt. The error is unexpected EOF. Maybe it got truncated when uploading?

**Comment by klazuka** [comment]
FYI I'm adding some performance tests (#513) to the project so that it's easier to monitor these things. If any of you know some open-source Elm projects which are very slow in IntelliJ, please let me know so that I can add them to the test suite.

**Comment by smucode** [comment]
Allocating more memory didn't seem to help. But Idea is using a lot of CPU, which i haven't noticed earlier. I tried to do some CPU profiling, but after enabling those VM options, idea just crashes :(

**Comment by WhileTruu** [comment]
I've been trying to manually mess up my test files for a while now, but I can't seem to repro it like this >.<

**Comment by klazuka** [comment]
Version 3.4.3 has some parser performance improvements. The problems you're seeing may (or may not) be fixed by this. Please let me know if there is any improvement.

**Comment by smucode** [comment]
I do see improvements, so I'm happy if you close this 👍

**Comment by Abubabubi** [comment]
Also seems good on my and @WhileTruu's side.

**Comment by klazuka** [comment]
Ok. There's more work to be done (#533), but I will close this for now.
