### ISSUE TITLE
Add an inspection to check for multiple declarations with the same name in the same file

### ISSUE THREAD

**Issue by MartinSStewart** [klazuka/intellij-elm#515]
In the following code I have duplicated the function `abc` but I've forgotten to rename the copy.
```elm
module Example exposing (abc)

abc = 0

abc = 0
```
intellij-elm will offer me the exposing intention for the second abc. If I use it, the exposing list becomes `exposing (abc, abc)`. If I use it again I get `exposing (abc, abc, abc)`, and so on.

The expected behavior would be for intellij-elm to warn me that I have the same function name used twice and disallow exposing the function multiple times.

**Comment by klazuka** [comment]
Yeah, we should at least indicate that there is an error.

Here's how the Elm compiler reports the error:
```
Detected errors in 1 module.                                         
-- NAME CLASH -------------------------------------------------- src/Example.elm

This file has multiple `abc` declarations. One here:

4| abc = 0
   ^^^
And another one here:

6| abc = 0
   ^^^
How can I know which one you want? Rename one of them!
```
