### ISSUE TITLE
Auto-discover for elm-format fails when using nvm on linux

### ISSUE THREAD

**Issue by r-k-b** [klazuka/intellij-elm#519]
When using nvm on Linux to manage node.js versions, the auto-discovery process will fail when checking the versions for elm-format and elm-test:

![Screenshot 2019-09-30 at 08 22 27](https://user-images.githubusercontent.com/2717397/65840368-779fc800-e35b-11e9-8232-647af08e3ad2.png)

The plugin seems to be assuming that the `node` executable is under `/usr/bin/env`; perhaps it would have more luck if it used the path in the node.js settings of the IDE?

![Screenshot 2019-09-30 at 08 24 32](https://user-images.githubusercontent.com/2717397/65840390-d7966e80-e35b-11e9-8bc9-82a162c8e72b.png)

(Possibly related to #252 ?)

**Comment by klazuka** [comment]
Unfortunately the Node.js/npm settings are part of a closed-source plugin from Jetbrains. So it would be difficult (and brittle) for me to depend on it.

I think what I need to do is just add more help text to the settings screen for weird situations like this (nvm).

**Comment by r-k-b** [comment]
So that help text would be something along the lines of "adjust your system to have a `/usr/bin/env/node`"? 

Or would the plugin support custom locations for the node executable?

**Comment by klazuka** [comment]
This plugin does not make any assumptions that node lives at `/usr/bin/env/node`. It's the npm-installed wrapper scripts for elm-format and elm-test that start with `#!/usr/bin/env node`. Which in turn relies on your `PATH` env var to locate node. 

Setting `PATH` for GUI apps is platform-dependent, and not obvious at all. So maybe I need to provide a separate text box for the path to `node` and then internally when I run `elm-format` or `elm-test`, I can augment the `PATH` to include whatever value you provide. As an optimization, I can try to pre-populate based on `.nvmrc`, if available.

**Comment by yonigibbs** [comment]
@r-k-b : some NVM-related docs have now been added [here](https://github.com/klazuka/intellij-elm/blob/master/docs/nvm.md). If this issue is still affecting you, maybe this might help you resolve the problem.

**Comment by r-k-b** [comment]
Thanks! That clears it up.
