### ISSUE TITLE
rename refactor does not pick up model update syntax

### ISSUE THREAD

**Issue by mordrax** [klazuka/intellij-elm#52]
In the image below, hitting Shift + F6 to rename incorrectly omits the ` { job | ` part of the function call.

![image](https://user-images.githubusercontent.com/4709169/43110734-ffbc0ff8-8f30-11e8-8267-898e4c4f1b91.png)

Elm plugin version: 1.1.1
Webstorm: 2018.1.5 ( #WS 181.5281.31 )

**Comment by ajalt** [comment]
I'm happy to do it, but I probably won't have time to work on it for a couple of days.
