### ISSUE TITLE
Go to declaration does not work for List

### ISSUE THREAD

**Issue by Abubabubi** [klazuka/intellij-elm#520]
If you try using "Declaration or Usages" command for list it cannot find declaration to go to.
This works for every other basic type I tried with.

Example to reproduce:
```module Main exposing (main)

import Html exposing (Html, text)


main : Html msg
main =
    let
        list : List Char
        list =
            [ 'a', 'b', 'c' ]
    in
    text <| String.fromList list
```

Tested on mac and ubuntu intellij with 3.4.3 plugin version.

**Comment by ajalt** [comment]
That's because there's no definition to go to. Unlike all the other built-in types, `List` is not actually defined anywhere outside of the compiler. There's an issue open for this problem here: https://github.com/elm/core/issues/1037
