### ISSUE TITLE
Feature request: Better name for generated list parameter

### ISSUE THREAD

**Issue by asoltysik** [klazuka/intellij-elm#526]
## The request
Currently, when generating the function from annotation, this:
`fun : List FooBar -> ()`
generates a following stub:
`fun list = `

It would be nice if it generated a more meaningful name, for example:
`fun fooBars = `

## A possible solution

I've looked into the code for a bit and it looks like the code for naming logic lives here:
https://github.com/klazuka/intellij-elm/blob/803728615b7174ea61e9be98d3493fa944f9d4d7/src/main/kotlin/org/elm/lang/core/types/TypeRendering.kt#L108

The change would probably involve adding additional pattern
`TyList -> renderListParam()`

And later something like this:

```
fun TyUnion.renderListParam(): String {
    return parameters.head.name.toElmLowerId() + "s"
}
```

I haven't tested or even compiled the above, just thought what I found could be useful for someone.

**Comment by klazuka** [comment]
@asoltysik that's a good idea. Thanks for the suggestion.
