### ISSUE TITLE
Compiler errors/warnings in IDE

### ISSUE THREAD

**Issue by jirisliva** [klazuka/intellij-elm#53]
Hello
Do you plan to show compiler errors/warning inside IDE?

I love this plugin but it's disturbing when I need to switch to console in order to see compiler output and then back to IDE.

**Comment by klazuka** [comment]
Yes, I am planning on improving the edit-compile cycle, and I have already started to lay the groundwork for it.

**Comment by jirisliva** [comment]
Thanks for answer. I am looking forward for this feature.
(Maybe one day .. I'll have some spare time to help with coding, bugfixing, whatever)
