### ISSUE TITLE
Type mixups in 3.4.3

### ISSUE THREAD

**Issue by smucode** [klazuka/intellij-elm#531]
I'm still seeing some type mixups in 3.4.3

![image](https://user-images.githubusercontent.com/502358/66459064-87628f00-ea74-11e9-92ce-2747952520dc.png)

In this file i have the imports: 

```
import GraphApi.Key as Key
import NodeApi.NodeTypes exposing (SavedSearch)
```

The custom type is defined in another file with the signature:

`UserApiResponse ( String, Query ) ( WebData User )`

And this file has the imports

```
import GraphApi.Key exposing (Key)
import NodeApi.NodeTypes exposing (User, ...)
```

**Comment by ajalt** [comment]
Thanks for the report!

Type lookup is resolving to the wrong element, but I'm not sure why without more information. Are you able to make an sscce for this?

**Comment by smucode** [comment]
Haven't been able to narrow it down to an sscce yet. But it's often the same types, or types from a specific module that get's mixed up. This module resides in a separate `source-directories` entry, could that be the problem?

**Comment by ajalt** [comment]
Yes, it's probably related to that. We have to look up declarations by name in a few places, and we've had similar bug before where we retrieve the wrong declaration due to similar reasons. If you manage to narrow it down to an sscce, this should probably be straight forward to fix.
