### ISSUE TITLE
Mismatching types resulting from a case-of expression is not reported as an error

### ISSUE THREAD

**Issue by viktor-ferenczi** [klazuka/intellij-elm#537]
GoLand 2019.2.3
Elm plugin 3.4.3

Example code:

```elm
view : Maybe String -> Html msg
view text =
    case text of
        Just a ->
            Html.text a

        Nothing ->
            [ Html.text "" ]
```

Elm plugin shows no error in IDE:

![image](https://user-images.githubusercontent.com/1848514/66709190-fe42a500-ed5e-11e9-9c6b-ec53398ec494.png)

Elm compiler correctly reports:

```
Something is off with the 2nd branch of this `case` expression:

115|             [ Html.text "" ]

                 ^^^^^^^^^^^^^^^^
The 2nd branch is a list of                                                                     
Detected errors in 1 module.

 type:

    List (Html msg)

But the type annotation on `view` says it should be:

    Html msg
```

**Comment by ajalt** [comment]
Hm, the error is reported correctly for me with plugin version 3.4.6 and GoLand 2019.3. Is your type inspection disabled?
![Capture](https://user-images.githubusercontent.com/1109214/71841219-c4d6b880-3073-11ea-8471-8c74cfcef71d.PNG)

**Comment by klazuka** [comment]
@viktor-ferenczi please try upgrading to 3.4.6. That version includes an important fix for a caching bug related to type inference.

**Comment by viktor-ferenczi** [comment]
I can confirm that 3.4.6 works correctly with my example above. Tested in GoLand.
