### ISSUE TITLE
Dead link in github repo description

### ISSUE THREAD

**Issue by MartinSStewart** [klazuka/intellij-elm#542]
Following the link in
> Elm language support for IntelliJ, WebStorm, PhpStorm and PyCharm (JetBrains) https://klazuka.github.io/intellij-elm/

leads to 

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/5068391/67216362-5e9eaa00-f423-11e9-9d1e-7148efa32e70.png">

**Comment by klazuka** [comment]
Thanks! Fixed now.
