### ISSUE TITLE
Live templates included on comment lines

### ISSUE THREAD

**Issue by yonigibbs** [klazuka/intellij-elm#543]
When typing certain characters (e.g. `t`) in a line which is a comment, the live templates for that character are shown. This isn't what happens in, say, Java or Kotlin code (no live templates are shown on comment lines).  For example in the gif below I type `-- t` then a live template shows up.  Additionally, if I now hit space (see note below) or tab, the live template will complete, and do something like add some code in the middle of my comment:

![elm-live-template-on-comment](https://user-images.githubusercontent.com/39593145/67239387-02e61800-f447-11e9-8cd3-5235de5c9b92.gif)

I wonder if all (or maybe just some) of the live templates should not be activated when writing on a comment line?

_Note_: hitting space completed the live template for me on one IntelliJ instance, but not another. Not sure which setting is at work here. Initially I thought it was "Insert selected suggestion by pressing space..." (shown below), but updating that setting didn't seem to have any impact so I'm not sure. Either way, I think that on a comment line in might be best for live templates not to be activated.

![code-completion-settings](https://user-images.githubusercontent.com/39593145/67239491-3759d400-f447-11e9-8a0c-d9805448b424.png)

**Comment by yonigibbs** [comment]
@klazuka, I'd be interested in trying to resolve this issue if you're happy with that? (I'm a Kotlin developer and have been using Elm for the last few weeks, using your plugin, so would enjoy getting involved in the project). I had a look and from what I can see the issue is that there is only one `TemplateContextType`, namely `ElmLiveTemplateContext`.  All the live templates in `/resources/liveTemplates/Elm.xml` refer to this context. This context's logic is simply based on the file extension. I had a look at the Java template contexts from IntelliJ and they have two separate ones: `JavaCommentContextType` and `JavaCodeContextType`. So two options that could be considered are:

1. Replace the existing `ElmLiveTemplateContext` with two separate contexts: one for code and one for comments. Then update `Elm.xml` and make some/all of the templates refer to the code context, or specifically state that they are disabled for the comment context.
1. If all the live templates apply only to code and will never apply to comments, keep just the single `ElmLiveTemplateContext`, and add to it logic to exclude lines which are comments.

In either case, the logic for deciding whether the user is on a comment or not has to be added somewhere. This can basically be copied from `JavaCommentContextType`. So if for example you decide that option 2 above is the best choice, `ElmLiveTemplateContext` could be updated with something like this:

```
class ElmLiveTemplateContext : TemplateContextType("ELM", "Elm") {

    override fun isInContext(file: PsiFile, offset: Int) =
            file.name.endsWith(".elm") && !isCommentLine(file, offset)

    private fun isCommentLine(file: PsiFile, offset: Int): Boolean {
        var element = file.findElementAt(offset)
        if (element is PsiWhiteSpace && offset > 0) {
            element = file.findElementAt(offset - 1)
        }
        return PsiTreeUtil.getParentOfType(element, PsiComment::class.java, false) != null
    }
}
```

(The `isCommentLine` method, and the call to it, are new.)

Anyway, just a suggestion. I'm not sure if this is the right solution or not as I'm new to the IntelliJ plugin framework. But if you're happy for me to go ahead with this let me know which option you prefer (and any comments/suggestions you have) and I'll submit a PR.

Thanks.

**Comment by yonigibbs** [comment]
Thanks @ajalt and @klazuka!  Much appreciated.

**Comment by klazuka** [comment]
@yonigibbs sorry for the long delay in responding. I got behind on my Github notifications, and one thing lead to another. Thanks for raising the issue and suggesting some fixes.

You're welcome to make other contributions to the project. My only advice would be to look at the [IntelliJ Rust plugin](https://github.com/intellij-rust/intellij-rust) for guidance when adding a new feature, as they generally have a very good solution and, most importantly, they have figured out a smart way to write tests for the feature.

**Comment by yonigibbs** [comment]
Will do!  Thanks.
