### ISSUE TITLE
It would be nice if 'Elm Compiler' > 'Build Elm Project' would hint 'a type annotation' example

### ISSUE THREAD

**Issue by HenkPoley** [klazuka/intellij-elm#545]
Hitting 'Build Elm Project' on the [first Elm Guide JSON example](https://guide.elm-lang.org/effects/json.html), says in the Event Log:
```
Cannot find your Elm app's main entry point. Please make sure that it has a type annotation.
```

Note that there is no hint which "a" type annotation would be appropriate.

If you would just suggest to _for example_ inject:
```elm
-- If you don't know main's type annotation, on the next run the Elm compiler will probably suggest the proper type annotation
main : Program Never Never Never
```

The compiler will next suggest the proper type annotation:
```
Detected problems in 1 module.
-- TYPE MISMATCH -------------------------------------------------- src/Main.elm

Something is off with the body of the `main` definition:

20|>  Browser.element
21|>    { init = init
22|>    , update = update
23|>    , subscriptions = subscriptions
24|>    , view = view
25|>    }

This `element` call produces:

    Program () Model Msg

But the type annotation on `main` says it should be:

    Program Never Never Never
```

I understand that it is _possible_ to create non-Program piece of Elm code, but I still expect that assumption that people who do not use type annotations are new to Elm is pretty safe.

Otherwise it might be possible for the 'Add type annotation' Quick Fix on `main =` to inspect what is inside the function, and figure out the proper type definition. But that is much harder 😅.

**Comment by ajalt** [comment]
I'm not sure I understand the issue. Running the "Add type annotation" quick fix on the main function of the example you posted correctly adds `main : Program () Model Msg`.

**Comment by HenkPoley** [comment]
It would add something like `main: undefined`

But 🤷‍♂️, you may put it on people who don't know need to learn.
