### ISSUE TITLE
Feature request: Suggest reuse of other functions just after writing a type signature

### ISSUE THREAD

**Issue by r-k-b** [klazuka/intellij-elm#549]
When I'm writing a type signature, is there any tooling that can show other implementations of that type sig in my codebase?
E.g., if I start writing "`foo : SomeEnum -> String`", the editor can say to me "There's already implementions of SomeEnum -> String _here_ and _here_, perhaps one of those is reusable?"

While there's ways to find matching implementations, the main thing this would solve is the writing of redundant functions when the author doesn't know to begin that search in the first place.

**Comment by klazuka** [comment]
I agree that for functions like you provided (mapping an enum to a string) it would be really useful. But what about functions with more broadly applicable parameters? e.g. `f : Int -> Int`. It would be confusing to suggest other implementations that are almost certainly not what you're looking for.

So I agree that it would be useful, but I'm doubtful about how it could be made to work in a variety of cases.
