### ISSUE TITLE
intellij-elm parser rejects valid pattern-matching syntax with {}

### ISSUE THREAD

**Issue by jhrcek** [klazuka/intellij-elm#561]
The "empty record" syntax in pattern matches is accepted by elm compiler, but is rejected by intellij-elm parser. This is very minor issue, which can be worked around easily bu using '_' instead of '{}' , but I wanted to bring this up just in case you're interested in this edge case. Feel free to close if you don't think it's worth fixing (for the sake of making this plugin's elm parser as close to elm's as possible).

```elm
module Main exposing (A(..), f)

type A
    = A { a : () }

f : A -> ()
f (A {}) = -- <- using {} in pattern match causes syntax error
    ()
```

**Comment by klazuka** [comment]
Thanks for the example, but I don't think it's worth matching this behavior. I suspect that the Elm compiler's behavior is accidental (or a holdover from when Elm's records were more featureful).
