### ISSUE TITLE
Can't set location of elm-test (installed with nvm)

### ISSUE THREAD

**Issue by yonigibbs** [klazuka/intellij-elm#564]
I have elm, elm-test and elm-format all installed by nvm.  As mentioned in some other issues (#519 and #252) this means Auto Discover doesn't work, so I have to manually type in the paths.  This works for elm and elm-format, but no path I try seems to be accepted for elm-test:

![elm test path](https://user-images.githubusercontent.com/39593145/70630176-0d40b900-1c23-11ea-8149-6966550cc673.png)

In case it's relevant, when I run `which elm-test` I get: `/home/yoni/.nvm/versions/node/v10.16.0/bin/elm-test`.  I tried this path too, and get the same error as in the screenshot above.

**Comment by yonigibbs** [comment]
Bit more information on this... looks like "Auto Discover" _does_ work, _if you install elm-test locally_.  In other words, if you have it installed globally with NVM, it doesn't seem to be found, but if you install it locally (e.g. `npm install elm-test --save-dev`) then it is found, in a path such as this:

    <your-project-path>/node_modules/.bin/elm-test

However the error above (the red text under the path to elm-test) still persists: `/usr/bin/env: 'node': No such file or directory`.

I've done some investigation and I think the cause of this is as follows...

The `elm-test` file which is auto-discovered has this content:

```
#!/usr/bin/env node
require("../lib/elm-test.js");
```

When a request is made to execute this file, the shebang line causes the system to look for `node` to execute this file, looking in the `$PATH` environment variable (as explained [here](https://stackoverflow.com/a/33510581/10326373)).  The problem is that the way the `elm-test` executable is run, the `$PATH` environment variable doesn't contain a path to `node`.  That's because the way the nvm install adds node to the path is by adding this content at the bottom of `.bashrc` (at least on my system that's how it did it):

```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```

`node` is added to `$PATH` when the `.nvm` script is executed, which is controlled by `.bashrc`.  When command-line stuff is executed from Java, the `.bashrc` file isn't picked up unless the shell is invoked as an interactive shell, as explained [here](https://stackoverflow.com/a/47438096/10326373).  So that's why the error occurs.

As a quick test, I updated `ElmTestCLI.queryVersion` and replaced the direct call to `elm-test` with a call to `/bin/bash -ic elm-test --version`, as shown below:

```
        val firstLine = try {
            // GeneralCommandLine(executablePath).withParameters("--version")            
           GeneralCommandLine("/bin/bash", "-ic", "$executablePath --version")
```

This now allowed the UI to show the right path.

So maybe something like that might be the start of a solution?  @klazuka / @ajalt, am happy to dig into this further an submit a PR if you think this might be the right approach.  Obviously this is a bit of a tricky one to test as it's highly dependent on the environment, how node is installed, etc.

**Comment by klazuka** [comment]
I'm not crazy about using a shell to run it since then it drags in a lot of other stuff that may complicate things in unexpected ways.

I think the right thing to do would be to allow the user to specify a path to `node` via our workspace settings UI and try to infer a good default based on the presence of `.nvmrc`. More details [here](https://github.com/klazuka/intellij-elm/issues/519#issuecomment-537536761).

It looks like `GeneralCommandLine.withEnvironment` would allow us to override the PATH to use the `node` path specified by the user.

The part that I'm most unsure about is how to surface it in the UI. Many people do not use `nvm`, so I don't want to make things more complicated for them. So I'd be inclinded to bury it a little.

Is it common for people that use `nvm` to have a `.nvmrc` file?

**Comment by yonigibbs** [comment]
Yeah, I hear what you're saying about the shell. I'm not sure about `.nvmrc` I'm afraid: not sure how often that's used. (It's not something I've used in the past, but certainly would be happy if the docs stated that in order to get this plugin working with nvm I need to create such a file.)

A UI option for a path to node sounds good. What about having a radio button option under the elm-test section, called "node discovery", or something like that, which has two options: "automatic" (the default) or "manual".  If "automatic", there would be nothing else to show, so it keeps the UI simple for most users.  If "manual" then a bunch of new options can be shown.  This is similar to how ESLint settings are handled in IntelliJ, e.g.

Automatic:
![eslint-automatic](https://user-images.githubusercontent.com/39593145/71415666-bdb3b180-2654-11ea-8150-43c12cb76144.png)

Manual:
![eslint-manual](https://user-images.githubusercontent.com/39593145/71415677-cb693700-2654-11ea-9aba-200640e73482.png)

**Comment by klazuka** [comment]
That seems good.

One area that might be problematic is when the user has installed `elm-format` and `elm-test` each with a separate version of node (e.g. /usr/bin/node for elm-format and a `nvm`-managed node for elm-test). And another consideration is the elm repl. We currently don't support it, but my understanding is that it, too, depends on node.

**Comment by yonigibbs** [comment]
Hmm... yup, tricky. Does that mean the user would need that "node discovery options" (or whatever name you think is best) separately for both `elm-format` and `elm-test`?  I think that would start to make the UI a bit complex.  Maybe there's a simpler solution here, which is to solve this by documentation in some way?  Like you say, most people don't use nvm, so maybe it's not really a big issue.  Maybe if the user is using nvm they can solve it in a different way, like writing a custom shell script or something, which itself calls elm-test.  Then in the plugin's settings, point to that custom shell script instead of elm-test itself?  Or is that too hacky?

**Comment by klazuka** [comment]
I guess we can just ignore the mixed environment for now.

What if there's no UI at all? Assuming that `nvm`-managed tools are installed in locations which can be identified as belonging to `nvm`, couldn't we just detect when a tool path is in an `nvm` location and synthesize something like your wrapper script?

Is there metadata in `~/.nvm` which could be used by "auto discover" to augment the set of `bin` paths that we search?

**Comment by yonigibbs** [comment]
I really like the idea of no UI: keep it simple for the user. But something I'm not sure is how would we even know if `nvm` is in the equation? The user could type in a path to `elm-test` (or `elm-format`) which might be under the control of `nvm`, but how would we know that? The installation directory of `nvm` could be anything, as stated [in their docs](https://github.com/nvm-sh/nvm#install--update-script):

> You can customize the install source, directory, profile, and version ...

While investigating this I actually started to have a bit of a rethink: maybe this whole problem of inheriting the path from stuff in `.bashrc` isn't something that the plugin should try to compensate for. It turns out this issue affects other folk too, e.g. [atom](https://github.com/atom/atom/issues/18318), and users just trying to use [npm with intellij](https://intellij-support.jetbrains.com/hc/en-us/community/posts/205964744-npm-is-installed-using-nvm-but-IntelliJ-doesn-t-know-about-it). In both those cases, the suggestion (including the response from JetBrains themselves in the second link there) is to launch the application (e.g. IntelliJ) in such a way that `.bashrc` will be taken into account.

So maybe simply documenting that would be the most pragmatic solution here? On my setup, I just managed to get everything working by changing the way IntelliJ is launched, as per [this suggestion from JetBrains](https://intellij-support.jetbrains.com/hc/en-us/community/posts/205964744-npm-is-installed-using-nvm-but-IntelliJ-doesn-t-know-about-it?page=1#community_comment_205060164). In other words I now launch IntelliJ using `/bin/bash -ic <path-to-intellij>` (in my case in a `.desktop` file).

If we add this to the documentation, would that suffice?  If so, I'm happy to draft up a bit of text summarising all this, and submitting it as a PR to the docs, if that would be of use.

**Comment by klazuka** [comment]
Sure, that would be fine with me. I don't use `nvm`, so I don't have good intuition for how it should all work. If this is how other projects are handling it, then that's fine with me.

One thing I would like to consider, though, is having a hyperlink from the Elm settings UI to some detailed instructions on dealing with `nvm`. That way the information is there but unobtrusive.

**Comment by yonigibbs** [comment]
Have created PR (#571) with suggested changes to the docs. How about I look at adding the hyperlink to the settings UI as part of #563, as that will require some changes to the same UI too? Or would you prefer a separate PR for that?

**Comment by klazuka** [comment]
Separate PR. The nvm instructions hyperlink belongs in the Elm workspace settings UI. The override on the tests directory belongs in the elm-test run configuration settings UI. 

I am going on a vacation today, so I won’t be able to review/respond much in the next couple of days, but I will try to check periodically.

**Comment by yonigibbs** [comment]
No worries at all.  Enjoy the vacation.  No rush on any of this stuff as far as I'm concerned.

**Comment by yonigibbs** [comment]
NVM-related docs now added [here](https://github.com/klazuka/intellij-elm/blob/master/docs/nvm.md) so I think this issue can now be considered closed.
