### ISSUE TITLE
CSS classes autocomplete for Attributes.class function

### ISSUE THREAD

**Issue by pravdomil** [klazuka/intellij-elm#579]
Consider this piece of elm view:`div [ class "container" ] [ text "hello"] `
there is no autocomplete when typing `container`. This should be also available for `Svg.Attributes.class`.

**Comment by ajalt** [comment]
I don't think it's feasible to suggest css class names, since there's no way to know what classes will be available in the document.

**Comment by pravdomil** [comment]
this is the same case as what classes suggest in html, twig or jsx, and it suggest something so I would do the same for elm

**Comment by ajalt** [comment]
The difference is that when editing an HTML document, you can see all the classes in the current document. That's not the case for arbitrary Elm code.
