### ISSUE TITLE
Import fix tooltip

### ISSUE THREAD

**Issue by pravdomil** [klazuka/intellij-elm#599]
In TypeScript there is sligtly different import dialog, that can import missing modules more quickly (you don't need to press enter twice and there is option to import them all at one), is that possible in Elm too?

**elm**
<img width="249" alt="image" src="https://user-images.githubusercontent.com/2387356/72470335-f15fa280-37e0-11ea-9617-1962cde90ff9.png">

**typescript**
<img width="566" alt="image" src="https://user-images.githubusercontent.com/2387356/72470253-c2e1c780-37e0-11ea-9f10-e1cc79ec679b.png">

**Comment by klazuka** [comment]
They are all built on the same plugin API, so it's definitely do-able. And, yeah, it would be nice. I just have never looked into it.

One thing that Java/Kotlin does is, if you pick something from auto-complete, it will insert the import automatically. I've always wanted to implement that for Elm, but I never got around to it. I think if we were to implement that, then that would make things even more seamless.

**Comment by pravdomil** [comment]
>  if you pick something from auto-complete, it will insert the import automatically

that would be really nice!
