### ISSUE TITLE
Import fix options

### ISSUE THREAD

**Issue by pravdomil** [klazuka/intellij-elm#606]
**First case**
I have a `type Model` defined in 3 modules: `Utils.One, Utils.Two, Three`.

And now I'm in Main.elm and I want to import `One.Model`. It offers module import `Three as One` as a first option, but it's obvious that I want to import `Utils.One as One`.

<img width="480" alt="image" src="https://user-images.githubusercontent.com/2387356/73266343-01ab5080-41d7-11ea-918f-a7dfb047e787.png">

**Second case**
Why import `Json.Encode as Decode`?

<img width="308" alt="image" src="https://user-images.githubusercontent.com/2387356/73266679-a9288300-41d7-11ea-9367-46ce44711ce8.png">

**Question**
Can I make it stop doing that? So if I have `Foo.Bar.Model` it can only offer modules those names ends with `Foo.Bar`? And not all modules that have `Model` defined?

**Comment by Herteby** [comment]
I think this would be too restrictive. Some people for example like to use `import Json.Decode as JD`

A better solution I think would be if the options list was sorted by match score, like Levenstein distance. So then the most likely module would be the first choice.

**Comment by klazuka** [comment]
The current sorting is no good, so we should definitely fix it. We definitely want to show multiple candidates for the reason that @Herteby suggested. So the best solution would be to figure out the best way to rank the candidates.
