### ISSUE TITLE
elm.json generated by plugin uses non-current versions of some packages

### ISSUE THREAD

**Issue by yonigibbs** [klazuka/intellij-elm#609]
When creating a new project/module using the plugin, it generates an `elm.json`. The versions of some of the packages aren't the latest, for example:

* `elm/browser`: uses `1.0.1`, but `1.0.2` is the latest. (This means you don't get the newest version of the Elm debugger, which is how I happened to notice this problem.)
* `elm/core`: uses `1.0.2`, but `1.0.4` is the latest.
* `elm/json`: uses `1.1.2`, but `1.1.3` is the latest.

It would be good if the plugin used the latest version of the packages, or simulated what `elm init` does.

**Comment by yonigibbs** [comment]
@klazuka: this is hard-coded currently in `ElmModuleBuilder.kt`. One easy option would be to update the template `elm.json` in here. But obviously this same issue would recur in future when a new version of any of the core libraries is released. There's a TODO in the code here saying:

> request that something like a `--yes` flag be added to `elm init` CLI"

I'm wondering if it would be possible to spawn a process to run `elm -init` and supply an input stream to it to feed in the `y` when asked.

You OK for me to investigate that option? Or would you rather just update the hard-coded values just now? (Either way I'll submit a PR to fix this issue if that's OK.)

**Comment by klazuka** [comment]
@yonigibbs running `elm init` and spamming "y" on stdin seems like a good idea to me. I think that at the time I was holding out for improved Elm CLI, but now I've lost confidence in that happening any time soon.
