### ISSUE TITLE
Nvm instructions don't work for me

### ISSUE THREAD

**Issue by alexandru-calinoiu** [klazuka/intellij-elm#610]
When trying to run the IDE via the instructions provided in the nvm doc I get

```
bash:no job control in this shell” mean?
```

Any other way I can get around this?

**Comment by yonigibbs** [comment]
How are you trying to run IntelliJ?  Are you opening a bash shell and running it from in there?  Or are you doing something else like editing a `.desktop` file or something like that?

Does this article here help: https://stackoverflow.com/questions/11821378/what-does-bashno-job-control-in-this-shell-mean ?  (It suggests running `set -m`.)

**Comment by alexandru-calinoiu** [comment]
It has something to do with the installations from snap, I've downloaded the app and it worked.

**Comment by yonigibbs** [comment]
Hmm... strange, I've got it installed with snap and using NVM, and working for me.  Odd.  Glad you've got it working though!  You OK for this issue to be closed now?
