### ISSUE TITLE
In test intellij-elm can not find Test and Expect modules

### ISSUE THREAD

**Issue by jachin** [klazuka/intellij-elm#618]
This is not a huge problem (but it is a little annoying).

When I use `elm-test` from the command line everything works fine. However in WebStorm (with the `intellij-elm` plugin) the "Live Error Checking" is showing all my unit tests unable to find the testing libraries from [elm-explorations/test](https://package.elm-lang.org/packages/elm-explorations/test/1.2.2/). Have the specific error message at the bottom along with a screen shot.

The `elm-explorations/test` library is specified in my `elm.json` in the `test-dependencies` section.

The `tests` directory (where all the tests are) **is** listed in the `source-directories` section of the `elm.json` file.

Possibly one odd thing about my setup is that I'm using [elmproj](https://github.com/joeandaverde/elm-webpack-project-loader) but I don't think the intellij-elm plugin would care about that.

I'm afraid I can not remember exactly when this started happening, I don't think I had this problem a couple of months ago.

If it would help I could try to figure out how to install older versions of the plugin and see where the problem started.

Let me know if there are any more details I could provide that would be helpful.

(Also this is a wonderful project, y'all are doing great work)

```
You are trying to import a `Expect` module:  4| import Expect           ^^^^^^ I checked the "dependencies" and "source-directories" listed in your elm.json, but I cannot find it! Maybe it is a typo for one of these names?      Dict     Ease     Set     Base64  Hint: If it is not a typo, check the "dependencies" and "source-directories" of your elm.json to make sure all the packages you need are listed there! 
```

![Screen Shot 2020-02-26 at 4 14 40 PM](https://user-images.githubusercontent.com/42679/75393262-4a782700-58b3-11ea-8cc1-b2e23017f60b.png)

**Comment by klazuka** [comment]
What version of the plugin are you using? Have you tried doing "File -> Invalidate Caches / Restart"? Clearing the caches shouldn't be necessary, but we did make some changes related to dependencies and caches and stubs in the last couple of releases, so maybe something stale got left behind.

**Comment by jachin** [comment]
> What version of the plugin are you using? Have you tried doing "File -> Invalidate Caches / Restart"? Clearing the caches shouldn't be necessary, but we did make some changes related to dependencies and caches and stubs in the last couple of releases, so maybe something stale got left behind.

That's a good idea, I tried "Invalid Caches / Restart" but after the index finished, I'm still having the same issue.

The version of the plugin I'm using is 3.5.1.

**Comment by jachin** [comment]
Whoah... I found the problem. When I looked up the version of the "Elm" plugin I noticed I had another elm related plugin installed called "Elm External Tools"... I disabled that plugin and the errors went away, I think that plugin was the source of the errors.

Sorry for the noise.

Keep up the good work. Y'all are awesome!

**Comment by mingan** [comment]
I have the same problem, I assume I'm doing something wrong:

- plugin version 3.5.3 (just updated)
- Elm 0.19.1
- `elm-explorations/test` is under `test-dependencies`
- `elm-explorations/test` is listed under External Libraries
- `source-directories` of the project are not standard but nothing crazy:
   ```
    "source-directories": [
        "app/frontend/elm",
        "app/frontend/tests",
        // few others
    ]
   ```
- project type is application
- detached & attached `elm.json`, no effect
- tried to clear cache & restart, no effect
- adding `elm-explorations/test` to `dependencies` "solves" the issue
