### ISSUE TITLE
Regression: Import fix no longer works

### ISSUE THREAD

**Issue by pravdomil** [klazuka/intellij-elm#643]
```elm
module Foo exposing (..)
type Foo
    = Foo Bar
--        ^ can't import Bar
```
<img width="449" alt="image" src="https://user-images.githubusercontent.com/2387356/78923173-15f1b080-7a98-11ea-8692-5568a8c5b34c.png">

```elm
module Bar exposing (..)
type alias Bar =
    {}
```

Does not work at master and I think it works at 21c1fb8 = `v3.5.1`.

**Comment by klazuka** [comment]
Thanks for finding this. I'll fix it today and make a release.

**Comment by pravdomil** [comment]
thank you, now I'm using it and it looks good!

**Comment by pravdomil** [comment]
also found https://github.com/klazuka/intellij-elm/issues/635

**Comment by pravdomil** [comment]
well it do not cover this scenario
```elm
module Foo exposing (..)
a =
    Bar
--  ^ can't import Bar
```
```elm
module Bar exposing (..)
type alias Bar =
    {}
```
