### ISSUE TITLE
Generating json encoders / decoders not working

### ISSUE THREAD

**Issue by prolic** [klazuka/intellij-elm#671]
I tried PhpStorm, PyCharm Community Edition and IDEA Community Edition. I cannot get json encoders / decoders generated. There is no generate option available.

**Comment by klazuka** [comment]
How are you trying to do it? The UX is kinda hard to discover. They are generated from type annotations. See https://github.com/klazuka/intellij-elm/blob/master/docs/features/generate-function-json.md

Hopefully that will work for you.

**Comment by prolic** [comment]
@klazuka Thanks. Seems like it's only a problem if the type alias is defined in another file.
