### ISSUE TITLE
Plugin incompatible with latest IDE version due to upper version bound in plugin.xml, causes 3.2.1 to be installed

### ISSUE THREAD

**Issue by Herteby** [klazuka/intellij-elm#672]
After restarting WebStorm I noticed my Elm syntax highlighting had suddenly changed. I went into the Color Scheme settings for Elm and it seemed like they were different and more limited than before. At the time I didn't check what version of the Elm plugin I was using though. I tried uninstalling/reinstalling the plugin, and the version I got was 3.2.1.

**Comment by Herteby** [comment]
I tried downloading the zip and use "Install plugin from Disk", and got this error message:
![image](https://user-images.githubusercontent.com/6474685/88654348-8b2bd480-d0cd-11ea-8f84-d5b47354e5a3.png)

**Comment by Herteby** [comment]
I was able to fix it by going into intellij-elm-3.5.3.zip/intellij-elm/lib/eplug-3.5.3.jar/META-INF/plugin.xml and changing the idea-version tag :relieved: 

Here's the fixed version for anyone stumbling across this before it has been officially fixed: [intellij-elm-3.5.3.zip](https://github.com/klazuka/intellij-elm/files/4987715/intellij-elm-3.5.3.zip)

**Comment by klazuka** [comment]
I will submit a new build today.

**Comment by klazuka** [comment]
New release submitted to JetBrains for approval. You can download it [from here](https://github.com/klazuka/intellij-elm/releases/tag/v3.5.4) in the meantime.

**Comment by klazuka** [comment]
It's available now in the plugin repository.
