### ISSUE TITLE
Allow for exposing of custom types both with constructors and without

### ISSUE THREAD

**Issue by akselw** [klazuka/intellij-elm#676]
When exposing a custom type with `Option+Enter`, the only option is to expose the type without its constructors. While this is a good default, it would be nice to be able to expose the type with its constructors from the menu as well.

**Comment by klazuka** [comment]
Agreed. I didn't do this early on because I was keeping Elm 0.18 compatibility (which has different rules about exposing union constructors), and I didn't want to make the code more complicated. Now that I've removed support for 0.18, I suspect that this would be fairly easy to do.

**Comment by yonigibbs** [comment]
I'll look at implementing this.
