### ISSUE TITLE
Plugin doesn't recognize 0.19 modules

### ISSUE THREAD

**Issue by romariolopezc** [klazuka/intellij-elm#68]
![image](https://user-images.githubusercontent.com/6199588/44552852-3a491f80-a6f1-11e8-9f86-2a994c7b9459.png)

**Comment by klazuka** [comment]
@romariolopezc did you "attach" your `elm.json` file? There should have been a yellow bar at the top of your editor prompting you to select it.

Also, can you take a screenshot of the left-hand-side Project window. Beneath all your source code, there should be a section called "External Libraries". I want to see if `elm/browser` is in there.

**Comment by romariolopezc** [comment]
I mistakenly closed web storm when that bar popped out, I re-opened but the bar didn't showed again. Is there a way to select it manually?


<img width="279" alt="image" src="https://user-images.githubusercontent.com/6199588/44589626-a32aa900-a77e-11e8-879d-194e37197f5a.png">

**Comment by romariolopezc** [comment]
Fixed, thanks!
