### ISSUE TITLE
Possible to use Structural Search to find by type signature?

### ISSUE THREAD

**Issue by r-k-b** [klazuka/intellij-elm#730]
I've recently discovered IntelliJ's [Structural Search](https://www.jetbrains.com/help/idea/structural-search-and-replace.html) feature, and it seems that'd be a good way to have [a klaftertief-like search](https://klaftertief.github.io/elm-search/) within a project. Elm doesn't appear in the Structural Search language dropdown, though.

Has anyone already investigated supporting Structural Search for Elm?

**Comment by klazuka** [comment]
No, I have not looked into it.

**Comment by r-k-b** [comment]
Thanks! I've had a go, but it's a bit beyond me at the moment. Closing for now.
