### ISSUE TITLE
Importing a constructor for a custom type should import all values

### ISSUE THREAD

**Issue by jorgengranseth** [klazuka/intellij-elm#77]
In 0.19 the compiler won't let you import a single constructor for a custom type.

```
import Time exposing (Weekday)


someWeekday : Weekday
someWeekday =
    Thu
    ^^^
```
importing `Thu` here with `Alt + Enter` gives you

```
import Time exposing (Weekday(Thu))
```
when it should give you
```
import Time exposing (Weekday(..))
```

It should probably also highlight this in case of manual imports and prompt to replace with `(..)`:
```
import Time exposing (Weekday(Thu))
                              ^^^
```

**Comment by klazuka** [comment]
@jorgengranseth yep. This is shortcoming of supporting both 0.18 and 0.19.

The simple fix will be to always generate the "exposing all constructors" fragment, even on 0.18.

We could add an error inspection to find the individual, exposed constructors on 0.19, but that will have diminishing payoff as more and more people update to 0.19. It would be nice if I had a lot more time, though 😄

**Comment by jorgengranseth** [comment]
The simple fix is sufficient for the vast majority of cases - at least in my experience. 👌
