### ISSUE TITLE
Lexer/highlighter gets confused with string literals in some cases

### ISSUE THREAD

**Issue by jorgengranseth** [klazuka/intellij-elm#78]
The way the plugin handles strings often leads to error highlights when typing a string with a symbol in it:

```
helloWorld =
    "Hello, world!"
    ^             ^
```

This only seems to happen to the last string in a file (presumably because the string pattern matches across lines and uses the next `"` as the closing quote). Inserting any character before the first symbol resolves the highlighting for the string. There isn't actually any errors showing on the right bar, just error highlighting on the text (without a tooltip).

I think ideally quotes would be handled as for e.g. Java:

```
helloWorld =
    |
```

On typing a quote `"`, a quote is inserted at the cursor's position and one immediately after it.

```
helloWorld =
    "|"
```

If you type a `"` while the cursor is immediately to the left of another quote, the cursor is moved to the right of the `"` rather than inserting an additional quote.

```
helloWorld =
    ""|
```

**Comment by klazuka** [comment]
There were 2 good points in this issue. I want to keep this one focused on the lexer highlight error, which is a bug that has annoyed me for a long time, and I'd like to get it fixed.

I moved the rest of the stuff to about smart insertion of double-quotes and cursor behavior to issue #79.
