### ISSUE TITLE
Upgrading a package causes plugin to not see it

### ISSUE THREAD

**Issue by mordrax** [klazuka/intellij-elm#80]
1. Open webstorm
2. Upgrade a package by a major version ( in my case https://package.elm-lang.org/packages/jweir/elm-iso8601/4.0.3/ -> 5.0.0 )
3. Webstorm continues to underline the `import ISO8601` line until you exit and restart

**Comment by klazuka** [comment]
Can you try this workaround: in the Webstorm menu bar, select Tools -> Elm -> Refresh Elm Projects.

**Comment by mordrax** [comment]
I tried just now on my mac and could not reproduce it.

I had this error on my ubuntu machine at home and will try again this evening to confirm.
