### ISSUE TITLE
Unresolved reference for imported Module

### ISSUE THREAD

**Issue by romariolopezc** [klazuka/intellij-elm#81]
```elm
import String.Extra as String -- All String.Extra functions are available in String

str : String
str = String.humanize "romario" -- This is marked as Unresolved reference `humanize`
```

It compiles without errors

**Comment by klazuka** [comment]
@romariolopezc this was fixed in https://github.com/klazuka/intellij-elm/pull/72, but it hasn't yet been released. I will try to do a release by the end of the weekend.
