### ISSUE TITLE
Importing a module with an alias should 'hide' the full module name during name resolution

### ISSUE THREAD

**Issue by rikvdkleij** [klazuka/intellij-elm#93]
Thanks for creating this plugin.

I just tried the plugin and noticed that qualified imports are not supported. For example:
```
import Html as H
```

it looks like plugin only "sees" the `import Html`

**Comment by klazuka** [comment]
@rikvdkleij the plugin definitely *should* support importing a module and giving it an alias name using `as`. I just tested out your example, `import Html as H`, and I could do stuff like `H.div`, etc. without any problem.

Can you provide a few more details:
- What error are you seeing?
- Are you using Elm 0.18 or 0.19?
- Does it work fine if you just do a normal import? (e.g. just `import Html`)
- What version of the plugin are you using?
- What version of IntelliJ/WebStorm/etc?

**Comment by rikvdkleij** [comment]
- I do not see an error
- 0.19
- Code completion only works when I put caret on identifier
- 1.3.3
- 2018.2.4

I have created the project with https://github.com/halfzebra/create-elm-app and imported the `elm.json` Goto declaration works.

**Comment by rikvdkleij** [comment]
`import Browser as B`

Works for both `Browser` and `B`. I would expect only for `B`

**Comment by klazuka** [comment]
Thanks for the details.

As for your `import Browser as B` example, you are correct, `B` should hide `Browser`. I just haven't gotten around to implementing it. I'm working on bunch of name and package resolution things right now. I intend to fix it shortly.

Does that address the original problem you were having with `import Html as H` or is it a separate bug?

**Comment by rikvdkleij** [comment]
Yes, that address the original issue. My mistake.

Thanks!

**Comment by klazuka** [comment]
No worries. Just glad there's one bug and not two 😄. I see that you're also an intellij plugin developer. Hi 👋 .

**Comment by rikvdkleij** [comment]
Hi 😄 

Yes, still working on improving the IntelliJ-Haskell plugin. So I know how much work it is to develop an IntelliJ plugin 😄
