### ISSUE TITLE
"Unresolved reference" everywhere

### ISSUE THREAD

**Issue by QuinnFreedman** [klazuka/intellij-elm#95]
When opening elm source files, I get an `Unresolved reference` error on every function.

I had a small existing elm `0.19` project. Elm is installed and all dependencies are installed and listed in `elm.json`. Running `elm make` or `elm reactor` from the command line gives no errors.

* I went `File > New > Project from existing sources...`. Picked the directory containing my `elm.json`
* It gave me a message "no elm toolchain configured". I entered the path of my elm binary
* It gave me a message "no elm.json". I picked the right elm.json
* It didn't give any more messages, but every reference in every src file is marked as unresolved (including builtins like `|>` and `>>`) See the screen shot bleow.

Am I configuring something wrong? Or is this a bug? I'm on Windows with

elm version `0.19.0`
npm version `6.1.0`
intellij version:
```
IntelliJ IDEA 2017.2.6
Build #IU-172.4574.11, built on November 13, 2017
Licensed to Quinn Freedman
Subscription is active until August 25, 2019
For educational use only.
JRE: 1.8.0_152-release-915-b12 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

![image](https://user-images.githubusercontent.com/10150390/46911484-1359dd80-cf2b-11e8-807b-f2236688b7b6.png)

**Comment by klazuka** [comment]
Is anything listed under “external libraries” in the left-side project tree pane?

Another thing you can try is open the Elm tool window on the right side and click the refresh button. Alternatively, detach and re-attach the ‘elm.json’ file. 

One last thing, are you using the default location for your installed Elm packages (~/.elm/ equivalent on Windows)?

**Comment by klazuka** [comment]
If all else fails, in the IntelliJ menu, select File -> Invalidate Caches and then re-attach the elm.json file.

**Comment by rogererens** [comment]
I experience something very similar in the Elm Architecture Tutorial that I got via a git clone command and editing in PyCharm Professional 2018.2.

I chose the (default?) C:/Program Files(x86)/Elm/0.19/bin directory as the location for elm.exe.
I chose the elm-architecture-tutorial/elm.json file to attach to.

Under the "External Libraries" section of the Project Pane, I have elm/browser->1.0.0

Invalidating the Cache and re-attaching appears not to improve matters. Neither does closing the project, creating a new project by git cloning a fresh one and setting up the Elm-toolchain and attaching the elm.json from that new project.

![image](https://user-images.githubusercontent.com/907897/47150441-e4e75400-d2d6-11e8-8680-a1611d96e378.png)

**Comment by klazuka** [comment]
@rogererens it's strange that the `elm/browser` `1.0.0` directory is empty in the External Libraries section. Can you try right-clicking those folders and figure out what path in the file system it's looking at? And then can you also find out where the real `elm/browser` source code has been installed by Elm?

I'm guessing there's something wrong with the paths that I'm using on Windows in certain cases, so it'd be good to confirm what the correct location is for the global Elm package cache.

**Comment by rogererens** [comment]
The 'Show in Explorer' points me to 'C:\Users\roger\AppData\Roaming\elm\0.19.0\package\elm\browser'.
The real elm/browser source code is in ... [still searching...].
Uhm, I'm actually not sure what I'm looking for. Would that be Browser.elm?

If so, I probably have some interference between the Windows Subsystem for Linux, where I installed Ubuntu and within Ubuntu I installed elm:
C:\Users\roger\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\home\roger\.elm\0.19.0\package\elm\browser\1.0.0\src

**Comment by QuinnFreedman** [comment]
I tried refreshing/syncing/opening+closing everything I could think of when I first got this problem but noting worked. But then I opened up Intellij a few days later and it was fixed. I'm not sure what happened. I can't think of anything that could have changed.

**Comment by rogererens** [comment]
@QuinnFreedman can you share a screen shot of the External Libraries in the Project Pane to show me what I should expect to see?

**Comment by rogererens** [comment]
After uninstalling Ubuntu, Elm, the elm plugin for PyCharm, and cleaning up some directories under pycharm's config directory, I reinstalled Elm and the plugin.
I couldn't start 'elm repl' because node.js was missing, so I installed that, too.

Then, I created a new project using 'Check out from Version Control' and cloned the elm-architecture-tutorial.
Upon opening the example files (and setting up the Elm tool chain: i.e. point to the directory where elm.exe was installed, and attaching the Elm JSON project file), at least I had the elm/core showing up under the 'External Libraries' in the project pane.
Progress!

Only after running 'elm reactor' from the command line in the elm-architecture-tutorial directory, the other packages showed up under 'External Libraries'. Yay!

Still, the 'Unresolved references' red squigly line shows up, though. That was cured by choosing the menu item 'Tools -> Elm -> Refresh Elm projects'.

Now I can also explain my previous problem better: I had Elm installed both in MS Windows and the WSL Ubuntu. I started a terminal, fired up bash (i.e. Ubuntu, because I like the CLI of bash better than CMD from Windows) and changed directory into the shared elm-architecture-tutorial folder. There I entered 'elm reactor' which obviously (only just now!) uses the WSL's elm compiler.
PyCharm, on the other hand, was fired up in MS Windows, and I had configured it to use the elm compiler installed in the Program Files (x86) directory. Were I to have entered 'elm reactor' in the CMD terminal, I assume the packages would have shown up in Pycharm's project pane.

So maybe the bottom line is that after creating the project, one should run the elm program before starting to edit.

**Comment by QuinnFreedman** [comment]
Here's a shot of my now working external dependencies. I'm not sure why PHP is there though...

![image](https://user-images.githubusercontent.com/10150390/47186181-bc268500-d2fd-11e8-914c-d4ca14dd48fc.png)

**Comment by rogererens** [comment]
Maybe you have set in your 'Settings -> Project: ...' set a PHP runtime for the value of 'Project Interpreter' (I reset mine to <No interpreter>)

**Comment by klazuka** [comment]
@rogererens wrote:
> So maybe the bottom line is that after creating the project, one should run the elm program before starting to edit.

Yes, this is 100% the case. The IntelliJ plugin does not install any packages for you. All it does is read your `elm.json` file and expect that all dependencies can be found in the place that the Elm compiler wants them.

I have some work planned in the future to improve error handling when attaching an `elm.json` file. Right now it just silently ignores any dependencies that should be installed but aren't.

**Comment by klazuka** [comment]
@QuinnFreedman wrote:
> Here's a shot of my now working external dependencies. I'm not sure why PHP is there though...

It's normal for the "External Libraries" section to contain stuff unrelated to Elm. It's a shared location for all the external libraries used by all of the language plugins that you have installed.

**Comment by klazuka** [comment]
I'm going to close this issue now. But I will definitely improve the error handling so that we don't run into a situation like this again. Thanks for reporting and investigating.

**Comment by DoctypeRosenthal** [comment]
I still get unresolved references. 
![image](https://user-images.githubusercontent.com/12626798/53404645-600ff380-39b6-11e9-9e88-31d822c89437.png)

Dependencies in elm-package.json

```json
{
    "version": "1.0.0",
    ...
    "source-directories": [
        "app/fas_ui/src/elm",
        "app/fas_ui/demo"
    ],
    "exposed-modules": [
        "Fas.Ui.Button",
        "Fas.Ui.Grid",
        "Fas.Ui.Grid.Cell",
        "Fas.Ui.Icon",
        "Fas.Ui.Typography",
        "Fas.Ui.List",
        "Fas.Ui.List.Item"
    ],
    "dependencies": {
        "NoRedInk/elm-decode-pipeline": "3.0.0 <= v < 4.0.0",
        "cuducos/elm-format-number": "6.0.1 <= v < 7.0.0",
        "elm-community/list-extra": "7.1.0 <= v < 8.0.0",
        "elm-lang/core": "5.1.1 <= v < 6.0.0",
        "elm-lang/html": "2.0.0 <= v < 3.0.0",
        "elm-lang/http": "1.0.0 <= v < 2.0.0",
        "elm-lang/navigation": "2.1.0 <= v < 3.0.0",
        "elm-lang/svg": "2.0.0 <= v < 3.0.0",
        "elm-lang/dom": "1.1.1 <= v < 2.0.0",
        "evancz/elm-sortable-table": "1.0.1 <= v < 2.0.0",
        "evancz/url-parser": "2.0.1 <= v < 3.0.0",
        "gampleman/elm-visualization": "1.6.1 <= v < 2.0.0",
        "mgold/elm-date-format": "1.6.0 <= v < 2.0.0",
        "stoeffel/elm-verify": "4.0.0 <= v < 5.0.0"
    },
    "elm-version": "0.18.0 <= v < 0.19.0"
}
```
And the elm-package.json is attached to the project.

What didn't help:
- invalidate cache and restart
- reinstall all Elm packages
- remove elm-stuff and reinstall and rebuild

**But** there is another elm-package.json file in a subfolder of the `tests/` folder with different, test-specific dependencies:

```json
{
    "version": "1.0.0",
    ...
    "source-directories": [
        "../src/elm",
        "."
    ],
    "exposed-modules": [],
    "dependencies": {
        "eeue56/elm-html-test": "5.2.0 <= v < 6.0.0",
        "elm-community/elm-test": "4.0.0 <= v < 5.0.0",
        "elm-lang/core": "5.1.1 <= v < 6.0.0",
        "elm-lang/html": "2.0.0 <= v < 3.0.0",
        "elm-lang/svg": "2.0.0 <= v < 3.0.0",
        "NoRedInk/elm-decode-pipeline": "3.0.0 <= v < 4.0.0",
        "elm-lang/http": "1.0.0 <= v < 2.0.0",
        "stoeffel/elm-verify": "4.0.0 <= v < 5.0.0",
        "evancz/elm-sortable-table": "1.0.1 <= v < 2.0.0",
        "mgold/elm-date-format": "1.6.0 <= v < 2.0.0",
        "gampleman/elm-visualization": "1.6.1 <= v < 2.0.0",
        "cuducos/elm-format-number": "6.0.1 <= v < 7.0.0",
        "elm-lang/navigation": "2.1.0 <= v < 3.0.0",
        "evancz/url-parser": "2.0.1 <= v < 3.0.0"
    },
    "elm-version": "0.18.0 <= v < 0.19.0"
}
```
Deleting that file *did* help! But now my imports in the test-Modules aren't working.
![image](https://user-images.githubusercontent.com/12626798/53405891-1e347c80-39b9-11e9-876e-fe86457c8ce5.png)

So the plugin seems to be handling multiple elm-package.jsons in subfolders not correctly.
Seems as if dependencies overwrite each other. Can you confirm this @klazuka ?

**Comment by klazuka** [comment]
@DoctypeRosenthal Yes, the Elm plugin is designed to support multiple Elm projects (`elm-package.json` files) within one IntelliJ project. 

However, the support for "package" projects (as opposed to applications) has a limitation: indirect dependencies are not currently loaded (full details on why [here](https://discourse.elm-lang.org/t/resolving-dependencies-in-elm-0-19-package-projects/2589)). I noticed in your first screenshot that it looked like there were 2 modules that were not resolved: `Dom` and `List.Extra`. Is it possible that these are indirect (transitive) dependencies of your package?

Another thing that might be causing trouble is "weird" `source-directories` configurations. Ideally they are not overlapping. Dealing with these edge cases is an area that needs improvement in the Elm plugin.

I should also mention that while the Elm plugin does still support 0.18, and I do test to make sure that it still works, it may not be as robust as 0.19 support.

**Comment by samidarko** [comment]
I had the same problem and I found some of my external dependencies where empty. Let's take `elm/core` 1.0.0, I checked `.elm/0.19.1/packages/elm/core/1.0.0` and it was actually really empty but 1.0.4 was not so I change the range in elm.json to `"elm/core": "1.0.4 <= v < 2.0.0"`. That's probably not a good solution but fixed the problem.

**Comment by gboersma** [comment]
Invalidate Caches / Restart worked for me.
